/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AdminDetails } from './admin-details';

/**
 * Response model for admins list with pagination and statistics.
 * @export
 * @interface AdminsResponse
 */
export interface AdminsResponse {
    /**
     * 
     * @type {Array<AdminDetails>}
     * @memberof AdminsResponse
     */
    'admins': Array<AdminDetails>;
    /**
     * 
     * @type {number}
     * @memberof AdminsResponse
     */
    'total': number;
    /**
     * 
     * @type {number}
     * @memberof AdminsResponse
     */
    'active': number;
    /**
     * 
     * @type {number}
     * @memberof AdminsResponse
     */
    'disabled': number;
}

