/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution Powered by Xray
 *
 * The version of the OpenAPI document: 0.8.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AdminCreate
 */
export interface AdminCreate {
    /**
     * 
     * @type {string}
     * @memberof AdminCreate
     */
    'username': string;
    /**
     * 
     * @type {boolean}
     * @memberof AdminCreate
     */
    'is_sudo': boolean;
    /**
     * 
     * @type {number}
     * @memberof AdminCreate
     */
    'telegram_id'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof AdminCreate
     */
    'discord_webhook'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AdminCreate
     */
    'users_usage'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof AdminCreate
     */
    'password': string;
}

