/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { UserNotificationEnable } from './user-notification-enable';

/**
 * Base model containing the core admin identification fields.
 * @export
 * @interface AdminContactInfo
 */
export interface AdminContactInfo {
    /**
     * 
     * @type {string}
     * @memberof AdminContactInfo
     */
    'username': string;
    /**
     * 
     * @type {number}
     * @memberof AdminContactInfo
     */
    'telegram_id'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof AdminContactInfo
     */
    'discord_webhook'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdminContactInfo
     */
    'sub_domain'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdminContactInfo
     */
    'profile_title'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdminContactInfo
     */
    'support_url'?: string | null;
    /**
     * 
     * @type {UserNotificationEnable}
     * @memberof AdminContactInfo
     */
    'notification_enable'?: UserNotificationEnable | null;
}

