/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdminNotificationEnable
 */
export interface AdminNotificationEnable {
    /**
     * 
     * @type {boolean}
     * @memberof AdminNotificationEnable
     */
    create?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AdminNotificationEnable
     */
    modify?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AdminNotificationEnable
     */
    _delete?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AdminNotificationEnable
     */
    resetUsage?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AdminNotificationEnable
     */
    login?: boolean;
}

/**
 * Check if a given object implements the AdminNotificationEnable interface.
 */
export function instanceOfAdminNotificationEnable(value: object): value is AdminNotificationEnable {
    return true;
}

export function AdminNotificationEnableFromJSON(json: any): AdminNotificationEnable {
    return AdminNotificationEnableFromJSONTyped(json, false);
}

export function AdminNotificationEnableFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminNotificationEnable {
    if (json == null) {
        return json;
    }
    return {
        
        'create': json['create'] == null ? undefined : json['create'],
        'modify': json['modify'] == null ? undefined : json['modify'],
        '_delete': json['delete'] == null ? undefined : json['delete'],
        'resetUsage': json['reset_usage'] == null ? undefined : json['reset_usage'],
        'login': json['login'] == null ? undefined : json['login'],
    };
}

export function AdminNotificationEnableToJSON(json: any): AdminNotificationEnable {
    return AdminNotificationEnableToJSONTyped(json, false);
}

export function AdminNotificationEnableToJSONTyped(value?: AdminNotificationEnable | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'create': value['create'],
        'modify': value['modify'],
        'delete': value['_delete'],
        'reset_usage': value['resetUsage'],
        'login': value['login'],
    };
}

