/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DownloadLink } from './DownloadLink';
import {
    DownloadLinkFromJSON,
    DownloadLinkFromJSONTyped,
    DownloadLinkToJSON,
    DownloadLinkToJSONTyped,
} from './DownloadLink';
import type { Platform } from './Platform';
import {
    PlatformFromJSON,
    PlatformFromJSONTyped,
    PlatformToJSON,
    PlatformToJSONTyped,
} from './Platform';

/**
 * 
 * @export
 * @interface ApplicationOutput
 */
export interface ApplicationOutput {
    /**
     * 
     * @type {string}
     * @memberof ApplicationOutput
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicationOutput
     */
    iconUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicationOutput
     */
    importUrl?: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof ApplicationOutput
     */
    description?: { [key: string]: string; };
    /**
     * 
     * @type {boolean}
     * @memberof ApplicationOutput
     */
    recommended?: boolean;
    /**
     * 
     * @type {Platform}
     * @memberof ApplicationOutput
     */
    platform: Platform;
    /**
     * 
     * @type {Array<DownloadLink>}
     * @memberof ApplicationOutput
     */
    downloadLinks: Array<DownloadLink>;
}



/**
 * Check if a given object implements the ApplicationOutput interface.
 */
export function instanceOfApplicationOutput(value: object): value is ApplicationOutput {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('platform' in value) || value['platform'] === undefined) return false;
    if (!('downloadLinks' in value) || value['downloadLinks'] === undefined) return false;
    return true;
}

export function ApplicationOutputFromJSON(json: any): ApplicationOutput {
    return ApplicationOutputFromJSONTyped(json, false);
}

export function ApplicationOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplicationOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'iconUrl': json['icon_url'] == null ? undefined : json['icon_url'],
        'importUrl': json['import_url'] == null ? undefined : json['import_url'],
        'description': json['description'] == null ? undefined : json['description'],
        'recommended': json['recommended'] == null ? undefined : json['recommended'],
        'platform': PlatformFromJSON(json['platform']),
        'downloadLinks': ((json['download_links'] as Array<any>).map(DownloadLinkFromJSON)),
    };
}

export function ApplicationOutputToJSON(json: any): ApplicationOutput {
    return ApplicationOutputToJSONTyped(json, false);
}

export function ApplicationOutputToJSONTyped(value?: ApplicationOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'icon_url': value['iconUrl'],
        'import_url': value['importUrl'],
        'description': value['description'],
        'recommended': value['recommended'],
        'platform': PlatformToJSON(value['platform']),
        'download_links': ((value['downloadLinks'] as Array<any>).map(DownloadLinkToJSON)),
    };
}

