/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BaseNotificationEnable
 */
export interface BaseNotificationEnable {
    /**
     * 
     * @type {boolean}
     * @memberof BaseNotificationEnable
     */
    create?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof BaseNotificationEnable
     */
    modify?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof BaseNotificationEnable
     */
    _delete?: boolean;
}

/**
 * Check if a given object implements the BaseNotificationEnable interface.
 */
export function instanceOfBaseNotificationEnable(value: object): value is BaseNotificationEnable {
    return true;
}

export function BaseNotificationEnableFromJSON(json: any): BaseNotificationEnable {
    return BaseNotificationEnableFromJSONTyped(json, false);
}

export function BaseNotificationEnableFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseNotificationEnable {
    if (json == null) {
        return json;
    }
    return {
        
        'create': json['create'] == null ? undefined : json['create'],
        'modify': json['modify'] == null ? undefined : json['modify'],
        '_delete': json['delete'] == null ? undefined : json['delete'],
    };
}

export function BaseNotificationEnableToJSON(json: any): BaseNotificationEnable {
    return BaseNotificationEnableToJSONTyped(json, false);
}

export function BaseNotificationEnableToJSONTyped(value?: BaseNotificationEnable | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'create': value['create'],
        'modify': value['modify'],
        'delete': value['_delete'],
    };
}

