/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { FragmentSettings } from './fragment-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { MuxSettingsOutput } from './mux-settings-output';
// May contain unused imports in some cases
// @ts-ignore
import type { NoiseSettings } from './noise-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { ProxyHostALPN } from './proxy-host-alpn';
// May contain unused imports in some cases
// @ts-ignore
import type { ProxyHostFingerprint } from './proxy-host-fingerprint';
// May contain unused imports in some cases
// @ts-ignore
import type { ProxyHostSecurity } from './proxy-host-security';
// May contain unused imports in some cases
// @ts-ignore
import type { TransportSettingsOutput } from './transport-settings-output';
// May contain unused imports in some cases
// @ts-ignore
import type { UserStatus } from './user-status';

/**
 * 
 * @export
 * @interface BaseHost
 */
export interface BaseHost {
    /**
     * 
     * @type {number}
     * @memberof BaseHost
     */
    'id'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof BaseHost
     */
    'remark': string;
    /**
     * 
     * @type {Set<string>}
     * @memberof BaseHost
     */
    'address'?: Set<string>;
    /**
     * 
     * @type {string}
     * @memberof BaseHost
     */
    'inbound_tag'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof BaseHost
     */
    'port'?: number | null;
    /**
     * 
     * @type {Set<string>}
     * @memberof BaseHost
     */
    'sni'?: Set<string> | null;
    /**
     * 
     * @type {Set<string>}
     * @memberof BaseHost
     */
    'host'?: Set<string> | null;
    /**
     * 
     * @type {string}
     * @memberof BaseHost
     */
    'path'?: string | null;
    /**
     * 
     * @type {ProxyHostSecurity}
     * @memberof BaseHost
     */
    'security'?: ProxyHostSecurity;
    /**
     * 
     * @type {Array<ProxyHostALPN>}
     * @memberof BaseHost
     */
    'alpn'?: Array<ProxyHostALPN> | null;
    /**
     * 
     * @type {ProxyHostFingerprint}
     * @memberof BaseHost
     */
    'fingerprint'?: ProxyHostFingerprint;
    /**
     * 
     * @type {boolean}
     * @memberof BaseHost
     */
    'allowinsecure'?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof BaseHost
     */
    'is_disabled'?: boolean;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof BaseHost
     */
    'http_headers'?: { [key: string]: string; } | null;
    /**
     * 
     * @type {TransportSettingsOutput}
     * @memberof BaseHost
     */
    'transport_settings'?: TransportSettingsOutput | null;
    /**
     * 
     * @type {MuxSettingsOutput}
     * @memberof BaseHost
     */
    'mux_settings'?: MuxSettingsOutput | null;
    /**
     * 
     * @type {FragmentSettings}
     * @memberof BaseHost
     */
    'fragment_settings'?: FragmentSettings | null;
    /**
     * 
     * @type {NoiseSettings}
     * @memberof BaseHost
     */
    'noise_settings'?: NoiseSettings | null;
    /**
     * 
     * @type {boolean}
     * @memberof BaseHost
     */
    'random_user_agent'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof BaseHost
     */
    'use_sni_as_host'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof BaseHost
     */
    'priority': number;
    /**
     * 
     * @type {Set<UserStatus>}
     * @memberof BaseHost
     */
    'status'?: Set<UserStatus> | null;
    /**
     * 
     * @type {string}
     * @memberof BaseHost
     */
    'ech_config_list'?: string | null;
}



