/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UsernameGenerationStrategy } from './UsernameGenerationStrategy';
import {
    UsernameGenerationStrategyFromJSON,
    UsernameGenerationStrategyFromJSONTyped,
    UsernameGenerationStrategyToJSON,
    UsernameGenerationStrategyToJSONTyped,
} from './UsernameGenerationStrategy';

/**
 * 
 * @export
 * @interface BulkUsersFromTemplate
 */
export interface BulkUsersFromTemplate {
    /**
     * 
     * @type {number}
     * @memberof BulkUsersFromTemplate
     */
    userTemplateId: number;
    /**
     * 
     * @type {string}
     * @memberof BulkUsersFromTemplate
     */
    note?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BulkUsersFromTemplate
     */
    username?: string | null;
    /**
     * 
     * @type {number}
     * @memberof BulkUsersFromTemplate
     */
    count: number;
    /**
     * 
     * @type {UsernameGenerationStrategy}
     * @memberof BulkUsersFromTemplate
     */
    strategy?: UsernameGenerationStrategy;
    /**
     * 
     * @type {number}
     * @memberof BulkUsersFromTemplate
     */
    startNumber?: number | null;
}



/**
 * Check if a given object implements the BulkUsersFromTemplate interface.
 */
export function instanceOfBulkUsersFromTemplate(value: object): value is BulkUsersFromTemplate {
    if (!('userTemplateId' in value) || value['userTemplateId'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function BulkUsersFromTemplateFromJSON(json: any): BulkUsersFromTemplate {
    return BulkUsersFromTemplateFromJSONTyped(json, false);
}

export function BulkUsersFromTemplateFromJSONTyped(json: any, ignoreDiscriminator: boolean): BulkUsersFromTemplate {
    if (json == null) {
        return json;
    }
    return {
        
        'userTemplateId': json['user_template_id'],
        'note': json['note'] == null ? undefined : json['note'],
        'username': json['username'] == null ? undefined : json['username'],
        'count': json['count'],
        'strategy': json['strategy'] == null ? undefined : UsernameGenerationStrategyFromJSON(json['strategy']),
        'startNumber': json['start_number'] == null ? undefined : json['start_number'],
    };
}

export function BulkUsersFromTemplateToJSON(json: any): BulkUsersFromTemplate {
    return BulkUsersFromTemplateToJSONTyped(json, false);
}

export function BulkUsersFromTemplateToJSONTyped(value?: BulkUsersFromTemplate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user_template_id': value['userTemplateId'],
        'note': value['note'],
        'username': value['username'],
        'count': value['count'],
        'strategy': UsernameGenerationStrategyToJSON(value['strategy']),
        'start_number': value['startNumber'],
    };
}

