/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { UserStatus } from './user-status';

/**
 * 
 * @export
 * @interface BulkUser
 */
export interface BulkUser {
    /**
     * 
     * @type {number}
     * @memberof BulkUser
     */
    'amount': number;
    /**
     * 
     * @type {Set<number>}
     * @memberof BulkUser
     */
    'group_ids'?: Set<number>;
    /**
     * 
     * @type {Set<number>}
     * @memberof BulkUser
     */
    'admins'?: Set<number>;
    /**
     * 
     * @type {Set<number>}
     * @memberof BulkUser
     */
    'users'?: Set<number>;
    /**
     * 
     * @type {Set<UserStatus>}
     * @memberof BulkUser
     */
    'status'?: Set<UserStatus>;
}

