/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const ConfigFormat = {
    Links: 'links',
    LinksBase64: 'links_base64',
    Xray: 'xray',
    SingBox: 'sing_box',
    Clash: 'clash',
    ClashMeta: 'clash_meta',
    Outline: 'outline',
    Block: 'block'
} as const;

export type ConfigFormat = typeof ConfigFormat[keyof typeof ConfigFormat];



