/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ConfigFormat = {
    Links: 'links',
    LinksBase64: 'links_base64',
    Xray: 'xray',
    SingBox: 'sing_box',
    Clash: 'clash',
    ClashMeta: 'clash_meta',
    Outline: 'outline',
    Block: 'block'
} as const;
export type ConfigFormat = typeof ConfigFormat[keyof typeof ConfigFormat];


export function instanceOfConfigFormat(value: any): boolean {
    for (const key in ConfigFormat) {
        if (Object.prototype.hasOwnProperty.call(ConfigFormat, key)) {
            if (ConfigFormat[key as keyof typeof ConfigFormat] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ConfigFormatFromJSON(json: any): ConfigFormat {
    return ConfigFormatFromJSONTyped(json, false);
}

export function ConfigFormatFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigFormat {
    return json as ConfigFormat;
}

export function ConfigFormatToJSON(value?: ConfigFormat | null): any {
    return value as any;
}

export function ConfigFormatToJSONTyped(value: any, ignoreDiscriminator: boolean): ConfigFormat {
    return value as ConfigFormat;
}

