/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CoreResponse } from './CoreResponse';
import {
    CoreResponseFromJSON,
    CoreResponseFromJSONTyped,
    CoreResponseToJSON,
    CoreResponseToJSONTyped,
} from './CoreResponse';

/**
 * 
 * @export
 * @interface CoreResponseList
 */
export interface CoreResponseList {
    /**
     * 
     * @type {number}
     * @memberof CoreResponseList
     */
    count: number;
    /**
     * 
     * @type {Array<CoreResponse>}
     * @memberof CoreResponseList
     */
    cores?: Array<CoreResponse>;
}

/**
 * Check if a given object implements the CoreResponseList interface.
 */
export function instanceOfCoreResponseList(value: object): value is CoreResponseList {
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function CoreResponseListFromJSON(json: any): CoreResponseList {
    return CoreResponseListFromJSONTyped(json, false);
}

export function CoreResponseListFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoreResponseList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'cores': json['cores'] == null ? undefined : ((json['cores'] as Array<any>).map(CoreResponseFromJSON)),
    };
}

export function CoreResponseListToJSON(json: any): CoreResponseList {
    return CoreResponseListToJSONTyped(json, false);
}

export function CoreResponseListToJSONTyped(value?: CoreResponseList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'cores': value['cores'] == null ? undefined : ((value['cores'] as Array<any>).map(CoreResponseToJSON)),
    };
}

