/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CoreResponse
 */
export interface CoreResponse {
    /**
     * 
     * @type {string}
     * @memberof CoreResponse
     */
    'name': string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof CoreResponse
     */
    'config': { [key: string]: any; };
    /**
     * 
     * @type {Set<string>}
     * @memberof CoreResponse
     */
    'exclude_inbound_tags': Set<string>;
    /**
     * 
     * @type {Set<string>}
     * @memberof CoreResponse
     */
    'fallbacks_inbound_tags': Set<string>;
    /**
     * 
     * @type {number}
     * @memberof CoreResponse
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof CoreResponse
     */
    'created_at': string;
}

