/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution Powered by Xray
 *
 * The version of the OpenAPI document: 0.8.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CoreStats
 */
export interface CoreStats {
    /**
     * 
     * @type {string}
     * @memberof CoreStats
     */
    'version': string;
    /**
     * 
     * @type {boolean}
     * @memberof CoreStats
     */
    'started': boolean;
    /**
     * 
     * @type {string}
     * @memberof CoreStats
     */
    'logs_websocket': string;
}

