/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateUserFromTemplate
 */
export interface CreateUserFromTemplate {
    /**
     * 
     * @type {number}
     * @memberof CreateUserFromTemplate
     */
    userTemplateId: number;
    /**
     * 
     * @type {string}
     * @memberof CreateUserFromTemplate
     */
    note?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateUserFromTemplate
     */
    username: string;
}

/**
 * Check if a given object implements the CreateUserFromTemplate interface.
 */
export function instanceOfCreateUserFromTemplate(value: object): value is CreateUserFromTemplate {
    if (!('userTemplateId' in value) || value['userTemplateId'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    return true;
}

export function CreateUserFromTemplateFromJSON(json: any): CreateUserFromTemplate {
    return CreateUserFromTemplateFromJSONTyped(json, false);
}

export function CreateUserFromTemplateFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateUserFromTemplate {
    if (json == null) {
        return json;
    }
    return {
        
        'userTemplateId': json['user_template_id'],
        'note': json['note'] == null ? undefined : json['note'],
        'username': json['username'],
    };
}

export function CreateUserFromTemplateToJSON(json: any): CreateUserFromTemplate {
    return CreateUserFromTemplateToJSONTyped(json, false);
}

export function CreateUserFromTemplateToJSONTyped(value?: CreateUserFromTemplate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user_template_id': value['userTemplateId'],
        'note': value['note'],
        'username': value['username'],
    };
}

