/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MuxSettingsInput } from './MuxSettingsInput';
import {
    MuxSettingsInputFromJSON,
    MuxSettingsInputFromJSONTyped,
    MuxSettingsInputToJSON,
    MuxSettingsInputToJSONTyped,
} from './MuxSettingsInput';
import type { TransportSettingsInput } from './TransportSettingsInput';
import {
    TransportSettingsInputFromJSON,
    TransportSettingsInputFromJSONTyped,
    TransportSettingsInputToJSON,
    TransportSettingsInputToJSONTyped,
} from './TransportSettingsInput';
import type { FragmentSettings } from './FragmentSettings';
import {
    FragmentSettingsFromJSON,
    FragmentSettingsFromJSONTyped,
    FragmentSettingsToJSON,
    FragmentSettingsToJSONTyped,
} from './FragmentSettings';
import type { NoiseSettings } from './NoiseSettings';
import {
    NoiseSettingsFromJSON,
    NoiseSettingsFromJSONTyped,
    NoiseSettingsToJSON,
    NoiseSettingsToJSONTyped,
} from './NoiseSettings';
import type { ProxyHostSecurity } from './ProxyHostSecurity';
import {
    ProxyHostSecurityFromJSON,
    ProxyHostSecurityFromJSONTyped,
    ProxyHostSecurityToJSON,
    ProxyHostSecurityToJSONTyped,
} from './ProxyHostSecurity';
import type { ProxyHostFingerprint } from './ProxyHostFingerprint';
import {
    ProxyHostFingerprintFromJSON,
    ProxyHostFingerprintFromJSONTyped,
    ProxyHostFingerprintToJSON,
    ProxyHostFingerprintToJSONTyped,
} from './ProxyHostFingerprint';
import type { ProxyHostALPN } from './ProxyHostALPN';
import {
    ProxyHostALPNFromJSON,
    ProxyHostALPNFromJSONTyped,
    ProxyHostALPNToJSON,
    ProxyHostALPNToJSONTyped,
} from './ProxyHostALPN';
import type { UserStatus } from './UserStatus';
import {
    UserStatusFromJSON,
    UserStatusFromJSONTyped,
    UserStatusToJSON,
    UserStatusToJSONTyped,
} from './UserStatus';

/**
 * 
 * @export
 * @interface CreateHost
 */
export interface CreateHost {
    /**
     * 
     * @type {number}
     * @memberof CreateHost
     */
    id?: number | null;
    /**
     * 
     * @type {string}
     * @memberof CreateHost
     */
    remark: string;
    /**
     * 
     * @type {Set<string>}
     * @memberof CreateHost
     */
    address?: Set<string>;
    /**
     * 
     * @type {string}
     * @memberof CreateHost
     */
    inboundTag?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CreateHost
     */
    port?: number | null;
    /**
     * 
     * @type {Set<string>}
     * @memberof CreateHost
     */
    sni?: Set<string> | null;
    /**
     * 
     * @type {Set<string>}
     * @memberof CreateHost
     */
    host?: Set<string> | null;
    /**
     * 
     * @type {string}
     * @memberof CreateHost
     */
    path?: string | null;
    /**
     * 
     * @type {ProxyHostSecurity}
     * @memberof CreateHost
     */
    security?: ProxyHostSecurity;
    /**
     * 
     * @type {Array<ProxyHostALPN>}
     * @memberof CreateHost
     */
    alpn?: Array<ProxyHostALPN> | null;
    /**
     * 
     * @type {ProxyHostFingerprint}
     * @memberof CreateHost
     */
    fingerprint?: ProxyHostFingerprint;
    /**
     * 
     * @type {boolean}
     * @memberof CreateHost
     */
    allowinsecure?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof CreateHost
     */
    isDisabled?: boolean;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof CreateHost
     */
    httpHeaders?: { [key: string]: string; } | null;
    /**
     * 
     * @type {TransportSettingsInput}
     * @memberof CreateHost
     */
    transportSettings?: TransportSettingsInput | null;
    /**
     * 
     * @type {MuxSettingsInput}
     * @memberof CreateHost
     */
    muxSettings?: MuxSettingsInput | null;
    /**
     * 
     * @type {FragmentSettings}
     * @memberof CreateHost
     */
    fragmentSettings?: FragmentSettings | null;
    /**
     * 
     * @type {NoiseSettings}
     * @memberof CreateHost
     */
    noiseSettings?: NoiseSettings | null;
    /**
     * 
     * @type {boolean}
     * @memberof CreateHost
     */
    randomUserAgent?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CreateHost
     */
    useSniAsHost?: boolean;
    /**
     * 
     * @type {number}
     * @memberof CreateHost
     */
    priority: number;
    /**
     * 
     * @type {Set<UserStatus>}
     * @memberof CreateHost
     */
    status?: Set<UserStatus> | null;
    /**
     * 
     * @type {string}
     * @memberof CreateHost
     */
    echConfigList?: string | null;
}



/**
 * Check if a given object implements the CreateHost interface.
 */
export function instanceOfCreateHost(value: object): value is CreateHost {
    if (!('remark' in value) || value['remark'] === undefined) return false;
    if (!('priority' in value) || value['priority'] === undefined) return false;
    return true;
}

export function CreateHostFromJSON(json: any): CreateHost {
    return CreateHostFromJSONTyped(json, false);
}

export function CreateHostFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateHost {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'remark': json['remark'],
        'address': json['address'] == null ? undefined : new Set(json['address']),
        'inboundTag': json['inbound_tag'] == null ? undefined : json['inbound_tag'],
        'port': json['port'] == null ? undefined : json['port'],
        'sni': json['sni'] == null ? undefined : new Set(json['sni']),
        'host': json['host'] == null ? undefined : new Set(json['host']),
        'path': json['path'] == null ? undefined : json['path'],
        'security': json['security'] == null ? undefined : ProxyHostSecurityFromJSON(json['security']),
        'alpn': json['alpn'] == null ? undefined : ((json['alpn'] as Array<any>).map(ProxyHostALPNFromJSON)),
        'fingerprint': json['fingerprint'] == null ? undefined : ProxyHostFingerprintFromJSON(json['fingerprint']),
        'allowinsecure': json['allowinsecure'] == null ? undefined : json['allowinsecure'],
        'isDisabled': json['is_disabled'] == null ? undefined : json['is_disabled'],
        'httpHeaders': json['http_headers'] == null ? undefined : json['http_headers'],
        'transportSettings': json['transport_settings'] == null ? undefined : TransportSettingsInputFromJSON(json['transport_settings']),
        'muxSettings': json['mux_settings'] == null ? undefined : MuxSettingsInputFromJSON(json['mux_settings']),
        'fragmentSettings': json['fragment_settings'] == null ? undefined : FragmentSettingsFromJSON(json['fragment_settings']),
        'noiseSettings': json['noise_settings'] == null ? undefined : NoiseSettingsFromJSON(json['noise_settings']),
        'randomUserAgent': json['random_user_agent'] == null ? undefined : json['random_user_agent'],
        'useSniAsHost': json['use_sni_as_host'] == null ? undefined : json['use_sni_as_host'],
        'priority': json['priority'],
        'status': json['status'] == null ? undefined : (new Set((json['status'] as Array<any>).map(UserStatusFromJSON))),
        'echConfigList': json['ech_config_list'] == null ? undefined : json['ech_config_list'],
    };
}

export function CreateHostToJSON(json: any): CreateHost {
    return CreateHostToJSONTyped(json, false);
}

export function CreateHostToJSONTyped(value?: CreateHost | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'remark': value['remark'],
        'address': value['address'] == null ? undefined : Array.from(value['address'] as Set<any>),
        'inbound_tag': value['inboundTag'],
        'port': value['port'],
        'sni': value['sni'] == null ? undefined : Array.from(value['sni'] as Set<any>),
        'host': value['host'] == null ? undefined : Array.from(value['host'] as Set<any>),
        'path': value['path'],
        'security': ProxyHostSecurityToJSON(value['security']),
        'alpn': value['alpn'] == null ? undefined : ((value['alpn'] as Array<any>).map(ProxyHostALPNToJSON)),
        'fingerprint': ProxyHostFingerprintToJSON(value['fingerprint']),
        'allowinsecure': value['allowinsecure'],
        'is_disabled': value['isDisabled'],
        'http_headers': value['httpHeaders'],
        'transport_settings': TransportSettingsInputToJSON(value['transportSettings']),
        'mux_settings': MuxSettingsInputToJSON(value['muxSettings']),
        'fragment_settings': FragmentSettingsToJSON(value['fragmentSettings']),
        'noise_settings': NoiseSettingsToJSON(value['noiseSettings']),
        'random_user_agent': value['randomUserAgent'],
        'use_sni_as_host': value['useSniAsHost'],
        'priority': value['priority'],
        'status': value['status'] == null ? undefined : (Array.from(value['status'] as Set<any>).map(UserStatusToJSON)),
        'ech_config_list': value['echConfigList'],
    };
}

