/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Discord
 */
export interface Discord {
    /**
     * 
     * @type {boolean}
     * @memberof Discord
     */
    'enable'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Discord
     */
    'token'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Discord
     */
    'proxy_url'?: string | null;
}

