/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { XrayFragmentSettings } from './XrayFragmentSettings';
import {
    XrayFragmentSettingsFromJSON,
    XrayFragmentSettingsFromJSONTyped,
    XrayFragmentSettingsToJSON,
    XrayFragmentSettingsToJSONTyped,
} from './XrayFragmentSettings';
import type { SingBoxFragmentSettings } from './SingBoxFragmentSettings';
import {
    SingBoxFragmentSettingsFromJSON,
    SingBoxFragmentSettingsFromJSONTyped,
    SingBoxFragmentSettingsToJSON,
    SingBoxFragmentSettingsToJSONTyped,
} from './SingBoxFragmentSettings';

/**
 * 
 * @export
 * @interface FragmentSettings
 */
export interface FragmentSettings {
    /**
     * 
     * @type {XrayFragmentSettings}
     * @memberof FragmentSettings
     */
    xray?: XrayFragmentSettings | null;
    /**
     * 
     * @type {SingBoxFragmentSettings}
     * @memberof FragmentSettings
     */
    singBox?: SingBoxFragmentSettings | null;
}

/**
 * Check if a given object implements the FragmentSettings interface.
 */
export function instanceOfFragmentSettings(value: object): value is FragmentSettings {
    return true;
}

export function FragmentSettingsFromJSON(json: any): FragmentSettings {
    return FragmentSettingsFromJSONTyped(json, false);
}

export function FragmentSettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): FragmentSettings {
    if (json == null) {
        return json;
    }
    return {
        
        'xray': json['xray'] == null ? undefined : XrayFragmentSettingsFromJSON(json['xray']),
        'singBox': json['sing_box'] == null ? undefined : SingBoxFragmentSettingsFromJSON(json['sing_box']),
    };
}

export function FragmentSettingsToJSON(json: any): FragmentSettings {
    return FragmentSettingsToJSONTyped(json, false);
}

export function FragmentSettingsToJSONTyped(value?: FragmentSettings | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'xray': XrayFragmentSettingsToJSON(value['xray']),
        'sing_box': SingBoxFragmentSettingsToJSON(value['singBox']),
    };
}

