/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SingBoxFragmentSettings } from './sing-box-fragment-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { XrayFragmentSettings } from './xray-fragment-settings';

/**
 * 
 * @export
 * @interface FragmentSettings
 */
export interface FragmentSettings {
    /**
     * 
     * @type {XrayFragmentSettings}
     * @memberof FragmentSettings
     */
    'xray'?: XrayFragmentSettings | null;
    /**
     * 
     * @type {SingBoxFragmentSettings}
     * @memberof FragmentSettings
     */
    'sing_box'?: SingBoxFragmentSettings | null;
}

