/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ShadowsocksMethods } from './shadowsocks-methods';
// May contain unused imports in some cases
// @ts-ignore
import type { XTLSFlows } from './xtlsflows';

/**
 * 
 * @export
 * @interface General
 */
export interface General {
    /**
     * 
     * @type {XTLSFlows}
     * @memberof General
     */
    'default_flow'?: XTLSFlows;
    /**
     * 
     * @type {ShadowsocksMethods}
     * @memberof General
     */
    'default_method'?: ShadowsocksMethods;
}



