/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GroupCreate
 */
export interface GroupCreate {
    /**
     * 
     * @type {string}
     * @memberof GroupCreate
     */
    name: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof GroupCreate
     */
    inboundTags: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof GroupCreate
     */
    isDisabled?: boolean;
}

/**
 * Check if a given object implements the GroupCreate interface.
 */
export function instanceOfGroupCreate(value: object): value is GroupCreate {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('inboundTags' in value) || value['inboundTags'] === undefined) return false;
    return true;
}

export function GroupCreateFromJSON(json: any): GroupCreate {
    return GroupCreateFromJSONTyped(json, false);
}

export function GroupCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'inboundTags': json['inbound_tags'],
        'isDisabled': json['is_disabled'] == null ? undefined : json['is_disabled'],
    };
}

export function GroupCreateToJSON(json: any): GroupCreate {
    return GroupCreateToJSONTyped(json, false);
}

export function GroupCreateToJSONTyped(value?: GroupCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'inbound_tags': value['inboundTags'],
        'is_disabled': value['isDisabled'],
    };
}

