/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GroupModify
 */
export interface GroupModify {
    /**
     * 
     * @type {string}
     * @memberof GroupModify
     */
    name: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof GroupModify
     */
    inboundTags?: Array<string> | null;
    /**
     * 
     * @type {boolean}
     * @memberof GroupModify
     */
    isDisabled?: boolean;
}

/**
 * Check if a given object implements the GroupModify interface.
 */
export function instanceOfGroupModify(value: object): value is GroupModify {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function GroupModifyFromJSON(json: any): GroupModify {
    return GroupModifyFromJSONTyped(json, false);
}

export function GroupModifyFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupModify {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'inboundTags': json['inbound_tags'] == null ? undefined : json['inbound_tags'],
        'isDisabled': json['is_disabled'] == null ? undefined : json['is_disabled'],
    };
}

export function GroupModifyToJSON(json: any): GroupModify {
    return GroupModifyToJSONTyped(json, false);
}

export function GroupModifyToJSONTyped(value?: GroupModify | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'inbound_tags': value['inboundTags'],
        'is_disabled': value['isDisabled'],
    };
}

