/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GRPCSettings
 */
export interface GRPCSettings {
    /**
     * 
     * @type {boolean}
     * @memberof GRPCSettings
     */
    'multi_mode'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof GRPCSettings
     */
    'idle_timeout'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof GRPCSettings
     */
    'health_check_timeout'?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof GRPCSettings
     */
    'permit_without_stream'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof GRPCSettings
     */
    'initial_windows_size'?: number | null;
}

