/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HMaxRequestTimes
 */
export interface HMaxRequestTimes {
}

/**
 * Check if a given object implements the HMaxRequestTimes interface.
 */
export function instanceOfHMaxRequestTimes(value: object): value is HMaxRequestTimes {
    return true;
}

export function HMaxRequestTimesFromJSON(json: any): HMaxRequestTimes {
    return HMaxRequestTimesFromJSONTyped(json, false);
}

export function HMaxRequestTimesFromJSONTyped(json: any, ignoreDiscriminator: boolean): HMaxRequestTimes {
    return json;
}

export function HMaxRequestTimesToJSON(json: any): HMaxRequestTimes {
    return HMaxRequestTimesToJSONTyped(json, false);
}

export function HMaxRequestTimesToJSONTyped(value?: HMaxRequestTimes | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

