/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModifyUserByTemplate
 */
export interface ModifyUserByTemplate {
    /**
     * 
     * @type {number}
     * @memberof ModifyUserByTemplate
     */
    userTemplateId: number;
    /**
     * 
     * @type {string}
     * @memberof ModifyUserByTemplate
     */
    note?: string | null;
}

/**
 * Check if a given object implements the ModifyUserByTemplate interface.
 */
export function instanceOfModifyUserByTemplate(value: object): value is ModifyUserByTemplate {
    if (!('userTemplateId' in value) || value['userTemplateId'] === undefined) return false;
    return true;
}

export function ModifyUserByTemplateFromJSON(json: any): ModifyUserByTemplate {
    return ModifyUserByTemplateFromJSONTyped(json, false);
}

export function ModifyUserByTemplateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModifyUserByTemplate {
    if (json == null) {
        return json;
    }
    return {
        
        'userTemplateId': json['user_template_id'],
        'note': json['note'] == null ? undefined : json['note'],
    };
}

export function ModifyUserByTemplateToJSON(json: any): ModifyUserByTemplate {
    return ModifyUserByTemplateToJSONTyped(json, false);
}

export function ModifyUserByTemplateToJSONTyped(value?: ModifyUserByTemplate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user_template_id': value['userTemplateId'],
        'note': value['note'],
    };
}

