/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NextPlanModel
 */
export interface NextPlanModel {
    /**
     * 
     * @type {number}
     * @memberof NextPlanModel
     */
    userTemplateId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof NextPlanModel
     */
    dataLimit?: number | null;
    /**
     * 
     * @type {number}
     * @memberof NextPlanModel
     */
    expire?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof NextPlanModel
     */
    addRemainingTraffic?: boolean;
}

/**
 * Check if a given object implements the NextPlanModel interface.
 */
export function instanceOfNextPlanModel(value: object): value is NextPlanModel {
    return true;
}

export function NextPlanModelFromJSON(json: any): NextPlanModel {
    return NextPlanModelFromJSONTyped(json, false);
}

export function NextPlanModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): NextPlanModel {
    if (json == null) {
        return json;
    }
    return {
        
        'userTemplateId': json['user_template_id'] == null ? undefined : json['user_template_id'],
        'dataLimit': json['data_limit'] == null ? undefined : json['data_limit'],
        'expire': json['expire'] == null ? undefined : json['expire'],
        'addRemainingTraffic': json['add_remaining_traffic'] == null ? undefined : json['add_remaining_traffic'],
    };
}

export function NextPlanModelToJSON(json: any): NextPlanModel {
    return NextPlanModelToJSONTyped(json, false);
}

export function NextPlanModelToJSONTyped(value?: NextPlanModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user_template_id': value['userTemplateId'],
        'data_limit': value['dataLimit'],
        'expire': value['expire'],
        'add_remaining_traffic': value['addRemainingTraffic'],
    };
}

