/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution Powered by Xray
 *
 * The version of the OpenAPI document: 0.8.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface NodeCreate
 */
export interface NodeCreate {
    /**
     * 
     * @type {string}
     * @memberof NodeCreate
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof NodeCreate
     */
    'address': string;
    /**
     * 
     * @type {number}
     * @memberof NodeCreate
     */
    'port'?: number;
    /**
     * 
     * @type {number}
     * @memberof NodeCreate
     */
    'api_port'?: number;
    /**
     * 
     * @type {number}
     * @memberof NodeCreate
     */
    'usage_coefficient'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof NodeCreate
     */
    'add_as_new_host'?: boolean;
}

