/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GeoFilseRegion } from './geo-filse-region';

/**
 * 
 * @export
 * @interface NodeGeoFilesUpdate
 */
export interface NodeGeoFilesUpdate {
    /**
     * 
     * @type {GeoFilseRegion}
     * @memberof NodeGeoFilesUpdate
     */
    'region'?: GeoFilseRegion;
}



