/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NodeCoreUpdate
 */
export interface NodeCoreUpdate {
    /**
     * 
     * @type {string}
     * @memberof NodeCoreUpdate
     */
    coreVersion?: string;
}

/**
 * Check if a given object implements the NodeCoreUpdate interface.
 */
export function instanceOfNodeCoreUpdate(value: object): value is NodeCoreUpdate {
    return true;
}

export function NodeCoreUpdateFromJSON(json: any): NodeCoreUpdate {
    return NodeCoreUpdateFromJSONTyped(json, false);
}

export function NodeCoreUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodeCoreUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'coreVersion': json['core_version'] == null ? undefined : json['core_version'],
    };
}

export function NodeCoreUpdateToJSON(json: any): NodeCoreUpdate {
    return NodeCoreUpdateToJSONTyped(json, false);
}

export function NodeCoreUpdateToJSONTyped(value?: NodeCoreUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'core_version': value['coreVersion'],
    };
}

