/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NodeUsageStat
 */
export interface NodeUsageStat {
    /**
     * 
     * @type {number}
     * @memberof NodeUsageStat
     */
    uplink: number;
    /**
     * 
     * @type {number}
     * @memberof NodeUsageStat
     */
    downlink: number;
    /**
     * 
     * @type {Date}
     * @memberof NodeUsageStat
     */
    periodStart: Date;
}

/**
 * Check if a given object implements the NodeUsageStat interface.
 */
export function instanceOfNodeUsageStat(value: object): value is NodeUsageStat {
    if (!('uplink' in value) || value['uplink'] === undefined) return false;
    if (!('downlink' in value) || value['downlink'] === undefined) return false;
    if (!('periodStart' in value) || value['periodStart'] === undefined) return false;
    return true;
}

export function NodeUsageStatFromJSON(json: any): NodeUsageStat {
    return NodeUsageStatFromJSONTyped(json, false);
}

export function NodeUsageStatFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodeUsageStat {
    if (json == null) {
        return json;
    }
    return {
        
        'uplink': json['uplink'],
        'downlink': json['downlink'],
        'periodStart': (new Date(json['period_start'])),
    };
}

export function NodeUsageStatToJSON(json: any): NodeUsageStat {
    return NodeUsageStatToJSONTyped(json, false);
}

export function NodeUsageStatToJSONTyped(value?: NodeUsageStat | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'uplink': value['uplink'],
        'downlink': value['downlink'],
        'period_start': ((value['periodStart']).toISOString()),
    };
}

