/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DataLimitResetStrategy } from './data-limit-reset-strategy';
// May contain unused imports in some cases
// @ts-ignore
import type { NodeConnectionType } from './node-connection-type';
// May contain unused imports in some cases
// @ts-ignore
import type { NodeStatus } from './node-status';

/**
 * 
 * @export
 * @interface NodeResponse
 */
export interface NodeResponse {
    /**
     * 
     * @type {string}
     * @memberof NodeResponse
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof NodeResponse
     */
    'address': string;
    /**
     * 
     * @type {number}
     * @memberof NodeResponse
     */
    'port'?: number;
    /**
     * 
     * @type {number}
     * @memberof NodeResponse
     */
    'api_port'?: number;
    /**
     * 
     * @type {number}
     * @memberof NodeResponse
     */
    'usage_coefficient'?: number;
    /**
     * 
     * @type {NodeConnectionType}
     * @memberof NodeResponse
     */
    'connection_type': NodeConnectionType;
    /**
     * 
     * @type {string}
     * @memberof NodeResponse
     */
    'server_ca': string;
    /**
     * 
     * @type {number}
     * @memberof NodeResponse
     */
    'keep_alive': number;
    /**
     * 
     * @type {number}
     * @memberof NodeResponse
     */
    'core_config_id': number | null;
    /**
     * 
     * @type {string}
     * @memberof NodeResponse
     */
    'api_key': string | null;
    /**
     * 
     * @type {number}
     * @memberof NodeResponse
     */
    'data_limit'?: number;
    /**
     * 
     * @type {DataLimitResetStrategy}
     * @memberof NodeResponse
     */
    'data_limit_reset_strategy'?: DataLimitResetStrategy;
    /**
     * 
     * @type {number}
     * @memberof NodeResponse
     */
    'reset_time'?: number;
    /**
     * 
     * @type {number}
     * @memberof NodeResponse
     */
    'default_timeout'?: number;
    /**
     * 
     * @type {number}
     * @memberof NodeResponse
     */
    'internal_timeout'?: number;
    /**
     * 
     * @type {number}
     * @memberof NodeResponse
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof NodeResponse
     */
    'xray_version': string | null;
    /**
     * 
     * @type {string}
     * @memberof NodeResponse
     */
    'node_version': string | null;
    /**
     * 
     * @type {NodeStatus}
     * @memberof NodeResponse
     */
    'status': NodeStatus;
    /**
     * 
     * @type {string}
     * @memberof NodeResponse
     */
    'message': string | null;
    /**
     * 
     * @type {number}
     * @memberof NodeResponse
     */
    'uplink'?: number;
    /**
     * 
     * @type {number}
     * @memberof NodeResponse
     */
    'downlink'?: number;
    /**
     * 
     * @type {number}
     * @memberof NodeResponse
     */
    'lifetime_uplink'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof NodeResponse
     */
    'lifetime_downlink'?: number | null;
}



