/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface NodeUsageStat
 */
export interface NodeUsageStat {
    /**
     * 
     * @type {number}
     * @memberof NodeUsageStat
     */
    'uplink': number;
    /**
     * 
     * @type {number}
     * @memberof NodeUsageStat
     */
    'downlink': number;
    /**
     * 
     * @type {string}
     * @memberof NodeUsageStat
     */
    'period_start': string;
}

