/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Period } from './Period';
import {
    PeriodFromJSON,
    PeriodFromJSONTyped,
    PeriodToJSON,
    PeriodToJSONTyped,
} from './Period';
import type { NodeUsageStat } from './NodeUsageStat';
import {
    NodeUsageStatFromJSON,
    NodeUsageStatFromJSONTyped,
    NodeUsageStatToJSON,
    NodeUsageStatToJSONTyped,
} from './NodeUsageStat';

/**
 * 
 * @export
 * @interface NodeUsageStatsList
 */
export interface NodeUsageStatsList {
    /**
     * 
     * @type {Period}
     * @memberof NodeUsageStatsList
     */
    period?: Period | null;
    /**
     * 
     * @type {Date}
     * @memberof NodeUsageStatsList
     */
    start: Date;
    /**
     * 
     * @type {Date}
     * @memberof NodeUsageStatsList
     */
    end: Date;
    /**
     * 
     * @type {{ [key: string]: Array<NodeUsageStat>; }}
     * @memberof NodeUsageStatsList
     */
    stats: { [key: string]: Array<NodeUsageStat>; };
}



/**
 * Check if a given object implements the NodeUsageStatsList interface.
 */
export function instanceOfNodeUsageStatsList(value: object): value is NodeUsageStatsList {
    if (!('start' in value) || value['start'] === undefined) return false;
    if (!('end' in value) || value['end'] === undefined) return false;
    if (!('stats' in value) || value['stats'] === undefined) return false;
    return true;
}

export function NodeUsageStatsListFromJSON(json: any): NodeUsageStatsList {
    return NodeUsageStatsListFromJSONTyped(json, false);
}

export function NodeUsageStatsListFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodeUsageStatsList {
    if (json == null) {
        return json;
    }
    return {
        
        'period': json['period'] == null ? undefined : PeriodFromJSON(json['period']),
        'start': (new Date(json['start'])),
        'end': (new Date(json['end'])),
        'stats': json['stats'],
    };
}

export function NodeUsageStatsListToJSON(json: any): NodeUsageStatsList {
    return NodeUsageStatsListToJSONTyped(json, false);
}

export function NodeUsageStatsListToJSONTyped(value?: NodeUsageStatsList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'period': PeriodToJSON(value['period']),
        'start': ((value['start']).toISOString()),
        'end': ((value['end']).toISOString()),
        'stats': value['stats'],
    };
}

