/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GeoFilseRegion } from './GeoFilseRegion';
import {
    GeoFilseRegionFromJSON,
    GeoFilseRegionFromJSONTyped,
    GeoFilseRegionToJSON,
    GeoFilseRegionToJSONTyped,
} from './GeoFilseRegion';

/**
 * 
 * @export
 * @interface NodeGeoFilesUpdate
 */
export interface NodeGeoFilesUpdate {
    /**
     * 
     * @type {GeoFilseRegion}
     * @memberof NodeGeoFilesUpdate
     */
    region?: GeoFilseRegion;
}



/**
 * Check if a given object implements the NodeGeoFilesUpdate interface.
 */
export function instanceOfNodeGeoFilesUpdate(value: object): value is NodeGeoFilesUpdate {
    return true;
}

export function NodeGeoFilesUpdateFromJSON(json: any): NodeGeoFilesUpdate {
    return NodeGeoFilesUpdateFromJSONTyped(json, false);
}

export function NodeGeoFilesUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodeGeoFilesUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'region': json['region'] == null ? undefined : GeoFilseRegionFromJSON(json['region']),
    };
}

export function NodeGeoFilesUpdateToJSON(json: any): NodeGeoFilesUpdate {
    return NodeGeoFilesUpdateToJSONTyped(json, false);
}

export function NodeGeoFilesUpdateToJSONTyped(value?: NodeGeoFilesUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'region': GeoFilseRegionToJSON(value['region']),
    };
}

