/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { NodeUsageStat } from './node-usage-stat';
// May contain unused imports in some cases
// @ts-ignore
import type { Period } from './period';

/**
 * 
 * @export
 * @interface NodeUsageStatsList
 */
export interface NodeUsageStatsList {
    /**
     * 
     * @type {Period}
     * @memberof NodeUsageStatsList
     */
    'period'?: Period | null;
    /**
     * 
     * @type {string}
     * @memberof NodeUsageStatsList
     */
    'start': string;
    /**
     * 
     * @type {string}
     * @memberof NodeUsageStatsList
     */
    'end': string;
    /**
     * 
     * @type {{ [key: string]: Array<NodeUsageStat>; }}
     * @memberof NodeUsageStatsList
     */
    'stats': { [key: string]: Array<NodeUsageStat>; };
}



