/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NodeRealtimeStats
 */
export interface NodeRealtimeStats {
    /**
     * 
     * @type {number}
     * @memberof NodeRealtimeStats
     */
    memTotal: number;
    /**
     * 
     * @type {number}
     * @memberof NodeRealtimeStats
     */
    memUsed: number;
    /**
     * 
     * @type {number}
     * @memberof NodeRealtimeStats
     */
    cpuCores: number;
    /**
     * 
     * @type {number}
     * @memberof NodeRealtimeStats
     */
    cpuUsage: number;
    /**
     * 
     * @type {number}
     * @memberof NodeRealtimeStats
     */
    incomingBandwidthSpeed: number;
    /**
     * 
     * @type {number}
     * @memberof NodeRealtimeStats
     */
    outgoingBandwidthSpeed: number;
}

/**
 * Check if a given object implements the NodeRealtimeStats interface.
 */
export function instanceOfNodeRealtimeStats(value: object): value is NodeRealtimeStats {
    if (!('memTotal' in value) || value['memTotal'] === undefined) return false;
    if (!('memUsed' in value) || value['memUsed'] === undefined) return false;
    if (!('cpuCores' in value) || value['cpuCores'] === undefined) return false;
    if (!('cpuUsage' in value) || value['cpuUsage'] === undefined) return false;
    if (!('incomingBandwidthSpeed' in value) || value['incomingBandwidthSpeed'] === undefined) return false;
    if (!('outgoingBandwidthSpeed' in value) || value['outgoingBandwidthSpeed'] === undefined) return false;
    return true;
}

export function NodeRealtimeStatsFromJSON(json: any): NodeRealtimeStats {
    return NodeRealtimeStatsFromJSONTyped(json, false);
}

export function NodeRealtimeStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodeRealtimeStats {
    if (json == null) {
        return json;
    }
    return {
        
        'memTotal': json['mem_total'],
        'memUsed': json['mem_used'],
        'cpuCores': json['cpu_cores'],
        'cpuUsage': json['cpu_usage'],
        'incomingBandwidthSpeed': json['incoming_bandwidth_speed'],
        'outgoingBandwidthSpeed': json['outgoing_bandwidth_speed'],
    };
}

export function NodeRealtimeStatsToJSON(json: any): NodeRealtimeStats {
    return NodeRealtimeStatsToJSONTyped(json, false);
}

export function NodeRealtimeStatsToJSONTyped(value?: NodeRealtimeStats | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mem_total': value['memTotal'],
        'mem_used': value['memUsed'],
        'cpu_cores': value['cpuCores'],
        'cpu_usage': value['cpuUsage'],
        'incoming_bandwidth_speed': value['incomingBandwidthSpeed'],
        'outgoing_bandwidth_speed': value['outgoingBandwidthSpeed'],
    };
}

