/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const NodeConnectionType = {
    Grpc: 'grpc',
    Rest: 'rest'
} as const;
export type NodeConnectionType = typeof NodeConnectionType[keyof typeof NodeConnectionType];


export function instanceOfNodeConnectionType(value: any): boolean {
    for (const key in NodeConnectionType) {
        if (Object.prototype.hasOwnProperty.call(NodeConnectionType, key)) {
            if (NodeConnectionType[key as keyof typeof NodeConnectionType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function NodeConnectionTypeFromJSON(json: any): NodeConnectionType {
    return NodeConnectionTypeFromJSONTyped(json, false);
}

export function NodeConnectionTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodeConnectionType {
    return json as NodeConnectionType;
}

export function NodeConnectionTypeToJSON(value?: NodeConnectionType | null): any {
    return value as any;
}

export function NodeConnectionTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): NodeConnectionType {
    return value as NodeConnectionType;
}

