/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NotFound
 */
export interface NotFound {
    /**
     * 
     * @type {string}
     * @memberof NotFound
     */
    detail?: string;
}

/**
 * Check if a given object implements the NotFound interface.
 */
export function instanceOfNotFound(value: object): value is NotFound {
    return true;
}

export function NotFoundFromJSON(json: any): NotFound {
    return NotFoundFromJSONTyped(json, false);
}

export function NotFoundFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotFound {
    if (json == null) {
        return json;
    }
    return {
        
        'detail': json['detail'] == null ? undefined : json['detail'],
    };
}

export function NotFoundToJSON(json: any): NotFound {
    return NotFoundToJSONTyped(json, false);
}

export function NotFoundToJSONTyped(value?: NotFound | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'detail': value['detail'],
    };
}

