/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Channel configuration for sending notifications to a specific entity
 * @export
 * @interface NotificationChannel
 */
export interface NotificationChannel {
    /**
     * 
     * @type {number}
     * @memberof NotificationChannel
     */
    telegramChatId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof NotificationChannel
     */
    telegramTopicId?: number | null;
    /**
     * 
     * @type {string}
     * @memberof NotificationChannel
     */
    discordWebhookUrl?: string | null;
}

/**
 * Check if a given object implements the NotificationChannel interface.
 */
export function instanceOfNotificationChannel(value: object): value is NotificationChannel {
    return true;
}

export function NotificationChannelFromJSON(json: any): NotificationChannel {
    return NotificationChannelFromJSONTyped(json, false);
}

export function NotificationChannelFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationChannel {
    if (json == null) {
        return json;
    }
    return {
        
        'telegramChatId': json['telegram_chat_id'] == null ? undefined : json['telegram_chat_id'],
        'telegramTopicId': json['telegram_topic_id'] == null ? undefined : json['telegram_topic_id'],
        'discordWebhookUrl': json['discord_webhook_url'] == null ? undefined : json['discord_webhook_url'],
    };
}

export function NotificationChannelToJSON(json: any): NotificationChannel {
    return NotificationChannelToJSONTyped(json, false);
}

export function NotificationChannelToJSONTyped(value?: NotificationChannel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'telegram_chat_id': value['telegramChatId'],
        'telegram_topic_id': value['telegramTopicId'],
        'discord_webhook_url': value['discordWebhookUrl'],
    };
}

