/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OnHoldTimeout
 */
export interface OnHoldTimeout {
}

/**
 * Check if a given object implements the OnHoldTimeout interface.
 */
export function instanceOfOnHoldTimeout(value: object): value is OnHoldTimeout {
    return true;
}

export function OnHoldTimeoutFromJSON(json: any): OnHoldTimeout {
    return OnHoldTimeoutFromJSONTyped(json, false);
}

export function OnHoldTimeoutFromJSONTyped(json: any, ignoreDiscriminator: boolean): OnHoldTimeout {
    return json;
}

export function OnHoldTimeoutToJSON(json: any): OnHoldTimeout {
    return OnHoldTimeoutToJSONTyped(json, false);
}

export function OnHoldTimeoutToJSONTyped(value?: OnHoldTimeout | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

