/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution Powered by Xray
 *
 * The version of the OpenAPI document: 0.8.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ProxyHostALPN } from './proxy-host-alpn';
// May contain unused imports in some cases
// @ts-ignore
import type { ProxyHostFingerprint } from './proxy-host-fingerprint';
// May contain unused imports in some cases
// @ts-ignore
import type { ProxyHostSecurity } from './proxy-host-security';

/**
 * 
 * @export
 * @interface ProxyHost
 */
export interface ProxyHost {
    /**
     * 
     * @type {string}
     * @memberof ProxyHost
     */
    'remark': string;
    /**
     * 
     * @type {string}
     * @memberof ProxyHost
     */
    'address': string;
    /**
     * 
     * @type {number}
     * @memberof ProxyHost
     */
    'port'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof ProxyHost
     */
    'sni'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProxyHost
     */
    'host'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProxyHost
     */
    'path'?: string | null;
    /**
     * 
     * @type {ProxyHostSecurity}
     * @memberof ProxyHost
     */
    'security'?: ProxyHostSecurity;
    /**
     * 
     * @type {ProxyHostALPN}
     * @memberof ProxyHost
     */
    'alpn'?: ProxyHostALPN;
    /**
     * 
     * @type {ProxyHostFingerprint}
     * @memberof ProxyHost
     */
    'fingerprint'?: ProxyHostFingerprint;
    /**
     * 
     * @type {boolean}
     * @memberof ProxyHost
     */
    'allowinsecure'?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof ProxyHost
     */
    'is_disabled'?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof ProxyHost
     */
    'mux_enable'?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof ProxyHost
     */
    'fragment_setting'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProxyHost
     */
    'noise_setting'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof ProxyHost
     */
    'random_user_agent'?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof ProxyHost
     */
    'use_sni_as_host'?: boolean | null;
}



