/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ProxyHostALPN = {
    Http11: 'http/1.1',
    H2: 'h2',
    H3: 'h3'
} as const;
export type ProxyHostALPN = typeof ProxyHostALPN[keyof typeof ProxyHostALPN];


export function instanceOfProxyHostALPN(value: any): boolean {
    for (const key in ProxyHostALPN) {
        if (Object.prototype.hasOwnProperty.call(ProxyHostALPN, key)) {
            if (ProxyHostALPN[key as keyof typeof ProxyHostALPN] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ProxyHostALPNFromJSON(json: any): ProxyHostALPN {
    return ProxyHostALPNFromJSONTyped(json, false);
}

export function ProxyHostALPNFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProxyHostALPN {
    return json as ProxyHostALPN;
}

export function ProxyHostALPNToJSON(value?: ProxyHostALPN | null): any {
    return value as any;
}

export function ProxyHostALPNToJSONTyped(value: any, ignoreDiscriminator: boolean): ProxyHostALPN {
    return value as ProxyHostALPN;
}

