/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const ProxyHostFingerprint = {
    Empty: '',
    Chrome: 'chrome',
    Firefox: 'firefox',
    Safari: 'safari',
    Ios: 'ios',
    Android: 'android',
    Edge: 'edge',
    _360: '360',
    Qq: 'qq',
    Random: 'random',
    Randomized: 'randomized',
    Randomizednoalpn: 'randomizednoalpn',
    Unsafe: 'unsafe'
} as const;

export type ProxyHostFingerprint = typeof ProxyHostFingerprint[keyof typeof ProxyHostFingerprint];



