/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const ProxyHostSecurity = {
    InboundDefault: 'inbound_default',
    None: 'none',
    Tls: 'tls'
} as const;

export type ProxyHostSecurity = typeof ProxyHostSecurity[keyof typeof ProxyHostSecurity];



