/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const ProxyHostALPN = {
    Http11: 'http/1.1',
    H2: 'h2',
    H3: 'h3'
} as const;

export type ProxyHostALPN = typeof ProxyHostALPN[keyof typeof ProxyHostALPN];



