/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution Powered by Xray
 *
 * The version of the OpenAPI document: 0.8.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Port } from './port';
// May contain unused imports in some cases
// @ts-ignore
import type { ProxyTypes } from './proxy-types';

/**
 * 
 * @export
 * @interface ProxyInbound
 */
export interface ProxyInbound {
    /**
     * 
     * @type {string}
     * @memberof ProxyInbound
     */
    'tag': string;
    /**
     * 
     * @type {ProxyTypes}
     * @memberof ProxyInbound
     */
    'protocol': ProxyTypes;
    /**
     * 
     * @type {string}
     * @memberof ProxyInbound
     */
    'network': string;
    /**
     * 
     * @type {string}
     * @memberof ProxyInbound
     */
    'tls': string;
    /**
     * 
     * @type {Port}
     * @memberof ProxyInbound
     */
    'port': Port;
}



