/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ScMaxEachPostBytes
 */
export interface ScMaxEachPostBytes {
}

/**
 * Check if a given object implements the ScMaxEachPostBytes interface.
 */
export function instanceOfScMaxEachPostBytes(value: object): value is ScMaxEachPostBytes {
    return true;
}

export function ScMaxEachPostBytesFromJSON(json: any): ScMaxEachPostBytes {
    return ScMaxEachPostBytesFromJSONTyped(json, false);
}

export function ScMaxEachPostBytesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScMaxEachPostBytes {
    return json;
}

export function ScMaxEachPostBytesToJSON(json: any): ScMaxEachPostBytes {
    return ScMaxEachPostBytesToJSONTyped(json, false);
}

export function ScMaxEachPostBytesToJSONTyped(value?: ScMaxEachPostBytes | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

