/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ScMinPostsIntervalMs
 */
export interface ScMinPostsIntervalMs {
}

/**
 * Check if a given object implements the ScMinPostsIntervalMs interface.
 */
export function instanceOfScMinPostsIntervalMs(value: object): value is ScMinPostsIntervalMs {
    return true;
}

export function ScMinPostsIntervalMsFromJSON(json: any): ScMinPostsIntervalMs {
    return ScMinPostsIntervalMsFromJSONTyped(json, false);
}

export function ScMinPostsIntervalMsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScMinPostsIntervalMs {
    return json;
}

export function ScMinPostsIntervalMsToJSON(json: any): ScMinPostsIntervalMs {
    return ScMinPostsIntervalMsToJSONTyped(json, false);
}

export function ScMinPostsIntervalMsToJSONTyped(value?: ScMinPostsIntervalMs | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

