/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SubscriptionOutput } from './SubscriptionOutput';
import {
    SubscriptionOutputFromJSON,
    SubscriptionOutputFromJSONTyped,
    SubscriptionOutputToJSON,
    SubscriptionOutputToJSONTyped,
} from './SubscriptionOutput';
import type { Telegram } from './Telegram';
import {
    TelegramFromJSON,
    TelegramFromJSONTyped,
    TelegramToJSON,
    TelegramToJSONTyped,
} from './Telegram';
import type { NotificationEnable } from './NotificationEnable';
import {
    NotificationEnableFromJSON,
    NotificationEnableFromJSONTyped,
    NotificationEnableToJSON,
    NotificationEnableToJSONTyped,
} from './NotificationEnable';
import type { NotificationSettingsOutput } from './NotificationSettingsOutput';
import {
    NotificationSettingsOutputFromJSON,
    NotificationSettingsOutputFromJSONTyped,
    NotificationSettingsOutputToJSON,
    NotificationSettingsOutputToJSONTyped,
} from './NotificationSettingsOutput';
import type { General } from './General';
import {
    GeneralFromJSON,
    GeneralFromJSONTyped,
    GeneralToJSON,
    GeneralToJSONTyped,
} from './General';
import type { Webhook } from './Webhook';
import {
    WebhookFromJSON,
    WebhookFromJSONTyped,
    WebhookToJSON,
    WebhookToJSONTyped,
} from './Webhook';
import type { Discord } from './Discord';
import {
    DiscordFromJSON,
    DiscordFromJSONTyped,
    DiscordToJSON,
    DiscordToJSONTyped,
} from './Discord';

/**
 * 
 * @export
 * @interface SettingsSchemaOutput
 */
export interface SettingsSchemaOutput {
    /**
     * 
     * @type {Telegram}
     * @memberof SettingsSchemaOutput
     */
    telegram?: Telegram | null;
    /**
     * 
     * @type {Discord}
     * @memberof SettingsSchemaOutput
     */
    discord?: Discord | null;
    /**
     * 
     * @type {Webhook}
     * @memberof SettingsSchemaOutput
     */
    webhook?: Webhook | null;
    /**
     * 
     * @type {NotificationSettingsOutput}
     * @memberof SettingsSchemaOutput
     */
    notificationSettings?: NotificationSettingsOutput | null;
    /**
     * 
     * @type {NotificationEnable}
     * @memberof SettingsSchemaOutput
     */
    notificationEnable?: NotificationEnable | null;
    /**
     * 
     * @type {SubscriptionOutput}
     * @memberof SettingsSchemaOutput
     */
    subscription?: SubscriptionOutput | null;
    /**
     * 
     * @type {General}
     * @memberof SettingsSchemaOutput
     */
    general?: General | null;
}

/**
 * Check if a given object implements the SettingsSchemaOutput interface.
 */
export function instanceOfSettingsSchemaOutput(value: object): value is SettingsSchemaOutput {
    return true;
}

export function SettingsSchemaOutputFromJSON(json: any): SettingsSchemaOutput {
    return SettingsSchemaOutputFromJSONTyped(json, false);
}

export function SettingsSchemaOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): SettingsSchemaOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'telegram': json['telegram'] == null ? undefined : TelegramFromJSON(json['telegram']),
        'discord': json['discord'] == null ? undefined : DiscordFromJSON(json['discord']),
        'webhook': json['webhook'] == null ? undefined : WebhookFromJSON(json['webhook']),
        'notificationSettings': json['notification_settings'] == null ? undefined : NotificationSettingsOutputFromJSON(json['notification_settings']),
        'notificationEnable': json['notification_enable'] == null ? undefined : NotificationEnableFromJSON(json['notification_enable']),
        'subscription': json['subscription'] == null ? undefined : SubscriptionOutputFromJSON(json['subscription']),
        'general': json['general'] == null ? undefined : GeneralFromJSON(json['general']),
    };
}

export function SettingsSchemaOutputToJSON(json: any): SettingsSchemaOutput {
    return SettingsSchemaOutputToJSONTyped(json, false);
}

export function SettingsSchemaOutputToJSONTyped(value?: SettingsSchemaOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'telegram': TelegramToJSON(value['telegram']),
        'discord': DiscordToJSON(value['discord']),
        'webhook': WebhookToJSON(value['webhook']),
        'notification_settings': NotificationSettingsOutputToJSON(value['notificationSettings']),
        'notification_enable': NotificationEnableToJSON(value['notificationEnable']),
        'subscription': SubscriptionOutputToJSON(value['subscription']),
        'general': GeneralToJSON(value['general']),
    };
}

