/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ShadowsocksMethods = {
    Aes128Gcm: 'aes-128-gcm',
    Aes256Gcm: 'aes-256-gcm',
    Chacha20IetfPoly1305: 'chacha20-ietf-poly1305',
    Xchacha20Poly1305: 'xchacha20-poly1305'
} as const;
export type ShadowsocksMethods = typeof ShadowsocksMethods[keyof typeof ShadowsocksMethods];


export function instanceOfShadowsocksMethods(value: any): boolean {
    for (const key in ShadowsocksMethods) {
        if (Object.prototype.hasOwnProperty.call(ShadowsocksMethods, key)) {
            if (ShadowsocksMethods[key as keyof typeof ShadowsocksMethods] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ShadowsocksMethodsFromJSON(json: any): ShadowsocksMethods {
    return ShadowsocksMethodsFromJSONTyped(json, false);
}

export function ShadowsocksMethodsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShadowsocksMethods {
    return json as ShadowsocksMethods;
}

export function ShadowsocksMethodsToJSON(value?: ShadowsocksMethods | null): any {
    return value as any;
}

export function ShadowsocksMethodsToJSONTyped(value: any, ignoreDiscriminator: boolean): ShadowsocksMethods {
    return value as ShadowsocksMethods;
}

