/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ShadowsocksMethods } from './ShadowsocksMethods';
import {
    ShadowsocksMethodsFromJSON,
    ShadowsocksMethodsFromJSONTyped,
    ShadowsocksMethodsToJSON,
    ShadowsocksMethodsToJSONTyped,
} from './ShadowsocksMethods';

/**
 * 
 * @export
 * @interface ShadowsocksSettings
 */
export interface ShadowsocksSettings {
    /**
     * 
     * @type {string}
     * @memberof ShadowsocksSettings
     */
    password?: string;
    /**
     * 
     * @type {ShadowsocksMethods}
     * @memberof ShadowsocksSettings
     */
    method?: ShadowsocksMethods;
}



/**
 * Check if a given object implements the ShadowsocksSettings interface.
 */
export function instanceOfShadowsocksSettings(value: object): value is ShadowsocksSettings {
    return true;
}

export function ShadowsocksSettingsFromJSON(json: any): ShadowsocksSettings {
    return ShadowsocksSettingsFromJSONTyped(json, false);
}

export function ShadowsocksSettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShadowsocksSettings {
    if (json == null) {
        return json;
    }
    return {
        
        'password': json['password'] == null ? undefined : json['password'],
        'method': json['method'] == null ? undefined : ShadowsocksMethodsFromJSON(json['method']),
    };
}

export function ShadowsocksSettingsToJSON(json: any): ShadowsocksSettings {
    return ShadowsocksSettingsToJSONTyped(json, false);
}

export function ShadowsocksSettingsToJSONTyped(value?: ShadowsocksSettings | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'password': value['password'],
        'method': ShadowsocksMethodsToJSON(value['method']),
    };
}

