/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SingBoxFragmentSettings
 */
export interface SingBoxFragmentSettings {
    /**
     * 
     * @type {boolean}
     * @memberof SingBoxFragmentSettings
     */
    'fragment'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SingBoxFragmentSettings
     */
    'fragment_fallback_delay'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof SingBoxFragmentSettings
     */
    'record_fragment'?: boolean;
}

