/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SingBoxFragmentSettings
 */
export interface SingBoxFragmentSettings {
    /**
     * 
     * @type {boolean}
     * @memberof SingBoxFragmentSettings
     */
    fragment?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SingBoxFragmentSettings
     */
    fragmentFallbackDelay?: string;
    /**
     * 
     * @type {boolean}
     * @memberof SingBoxFragmentSettings
     */
    recordFragment?: boolean;
}

/**
 * Check if a given object implements the SingBoxFragmentSettings interface.
 */
export function instanceOfSingBoxFragmentSettings(value: object): value is SingBoxFragmentSettings {
    return true;
}

export function SingBoxFragmentSettingsFromJSON(json: any): SingBoxFragmentSettings {
    return SingBoxFragmentSettingsFromJSONTyped(json, false);
}

export function SingBoxFragmentSettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): SingBoxFragmentSettings {
    if (json == null) {
        return json;
    }
    return {
        
        'fragment': json['fragment'] == null ? undefined : json['fragment'],
        'fragmentFallbackDelay': json['fragment_fallback_delay'] == null ? undefined : json['fragment_fallback_delay'],
        'recordFragment': json['record_fragment'] == null ? undefined : json['record_fragment'],
    };
}

export function SingBoxFragmentSettingsToJSON(json: any): SingBoxFragmentSettings {
    return SingBoxFragmentSettingsToJSONTyped(json, false);
}

export function SingBoxFragmentSettingsToJSONTyped(value?: SingBoxFragmentSettings | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fragment': value['fragment'],
        'fragment_fallback_delay': value['fragmentFallbackDelay'],
        'record_fragment': value['recordFragment'],
    };
}

