/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SubFormatEnable
 */
export interface SubFormatEnable {
    /**
     * 
     * @type {boolean}
     * @memberof SubFormatEnable
     */
    'links'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SubFormatEnable
     */
    'links_base64'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SubFormatEnable
     */
    'xray'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SubFormatEnable
     */
    'sing_box'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SubFormatEnable
     */
    'clash'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SubFormatEnable
     */
    'clash_meta'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SubFormatEnable
     */
    'outline'?: boolean;
}

