/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubFormatEnable
 */
export interface SubFormatEnable {
    /**
     * 
     * @type {boolean}
     * @memberof SubFormatEnable
     */
    links?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SubFormatEnable
     */
    linksBase64?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SubFormatEnable
     */
    xray?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SubFormatEnable
     */
    singBox?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SubFormatEnable
     */
    clash?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SubFormatEnable
     */
    clashMeta?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SubFormatEnable
     */
    outline?: boolean;
}

/**
 * Check if a given object implements the SubFormatEnable interface.
 */
export function instanceOfSubFormatEnable(value: object): value is SubFormatEnable {
    return true;
}

export function SubFormatEnableFromJSON(json: any): SubFormatEnable {
    return SubFormatEnableFromJSONTyped(json, false);
}

export function SubFormatEnableFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubFormatEnable {
    if (json == null) {
        return json;
    }
    return {
        
        'links': json['links'] == null ? undefined : json['links'],
        'linksBase64': json['links_base64'] == null ? undefined : json['links_base64'],
        'xray': json['xray'] == null ? undefined : json['xray'],
        'singBox': json['sing_box'] == null ? undefined : json['sing_box'],
        'clash': json['clash'] == null ? undefined : json['clash'],
        'clashMeta': json['clash_meta'] == null ? undefined : json['clash_meta'],
        'outline': json['outline'] == null ? undefined : json['outline'],
    };
}

export function SubFormatEnableToJSON(json: any): SubFormatEnable {
    return SubFormatEnableToJSONTyped(json, false);
}

export function SubFormatEnableToJSONTyped(value?: SubFormatEnable | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'links': value['links'],
        'links_base64': value['linksBase64'],
        'xray': value['xray'],
        'sing_box': value['singBox'],
        'clash': value['clash'],
        'clash_meta': value['clashMeta'],
        'outline': value['outline'],
    };
}

