/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConfigFormat } from './ConfigFormat';
import {
    ConfigFormatFromJSON,
    ConfigFormatFromJSONTyped,
    ConfigFormatToJSON,
    ConfigFormatToJSONTyped,
} from './ConfigFormat';

/**
 * 
 * @export
 * @interface SubRule
 */
export interface SubRule {
    /**
     * 
     * @type {string}
     * @memberof SubRule
     */
    pattern: string;
    /**
     * 
     * @type {ConfigFormat}
     * @memberof SubRule
     */
    target: ConfigFormat;
}



/**
 * Check if a given object implements the SubRule interface.
 */
export function instanceOfSubRule(value: object): value is SubRule {
    if (!('pattern' in value) || value['pattern'] === undefined) return false;
    if (!('target' in value) || value['target'] === undefined) return false;
    return true;
}

export function SubRuleFromJSON(json: any): SubRule {
    return SubRuleFromJSONTyped(json, false);
}

export function SubRuleFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubRule {
    if (json == null) {
        return json;
    }
    return {
        
        'pattern': json['pattern'],
        'target': ConfigFormatFromJSON(json['target']),
    };
}

export function SubRuleToJSON(json: any): SubRule {
    return SubRuleToJSONTyped(json, false);
}

export function SubRuleToJSONTyped(value?: SubRule | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pattern': value['pattern'],
        'target': ConfigFormatToJSON(value['target']),
    };
}

