/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ApplicationInput } from './application-input';
// May contain unused imports in some cases
// @ts-ignore
import type { SubFormatEnable } from './sub-format-enable';
// May contain unused imports in some cases
// @ts-ignore
import type { SubRule } from './sub-rule';

/**
 * 
 * @export
 * @interface SubscriptionInput
 */
export interface SubscriptionInput {
    /**
     * 
     * @type {string}
     * @memberof SubscriptionInput
     */
    'url_prefix'?: string;
    /**
     * 
     * @type {number}
     * @memberof SubscriptionInput
     */
    'update_interval'?: number;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionInput
     */
    'support_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionInput
     */
    'profile_title'?: string;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionInput
     */
    'announce'?: string;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionInput
     */
    'announce_url'?: string;
    /**
     * 
     * @type {Array<SubRule>}
     * @memberof SubscriptionInput
     */
    'rules': Array<SubRule>;
    /**
     * 
     * @type {SubFormatEnable}
     * @memberof SubscriptionInput
     */
    'manual_sub_request'?: SubFormatEnable;
    /**
     * 
     * @type {Array<ApplicationInput>}
     * @memberof SubscriptionInput
     */
    'applications'?: Array<ApplicationInput>;
    /**
     * 
     * @type {boolean}
     * @memberof SubscriptionInput
     */
    'allow_browser_config'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SubscriptionInput
     */
    'disable_sub_template'?: boolean;
}

