/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DataLimitResetStrategy } from './DataLimitResetStrategy';
import {
    DataLimitResetStrategyFromJSON,
    DataLimitResetStrategyFromJSONTyped,
    DataLimitResetStrategyToJSON,
    DataLimitResetStrategyToJSONTyped,
} from './DataLimitResetStrategy';
import type { Expire } from './Expire';
import {
    ExpireFromJSON,
    ExpireFromJSONTyped,
    ExpireToJSON,
    ExpireToJSONTyped,
} from './Expire';
import type { ProxyTableOutput } from './ProxyTableOutput';
import {
    ProxyTableOutputFromJSON,
    ProxyTableOutputFromJSONTyped,
    ProxyTableOutputToJSON,
    ProxyTableOutputToJSONTyped,
} from './ProxyTableOutput';
import type { OnHoldTimeout } from './OnHoldTimeout';
import {
    OnHoldTimeoutFromJSON,
    OnHoldTimeoutFromJSONTyped,
    OnHoldTimeoutToJSON,
    OnHoldTimeoutToJSONTyped,
} from './OnHoldTimeout';
import type { NextPlanModel } from './NextPlanModel';
import {
    NextPlanModelFromJSON,
    NextPlanModelFromJSONTyped,
    NextPlanModelToJSON,
    NextPlanModelToJSONTyped,
} from './NextPlanModel';
import type { UserStatus } from './UserStatus';
import {
    UserStatusFromJSON,
    UserStatusFromJSONTyped,
    UserStatusToJSON,
    UserStatusToJSONTyped,
} from './UserStatus';

/**
 * 
 * @export
 * @interface SubscriptionUserResponse
 */
export interface SubscriptionUserResponse {
    /**
     * 
     * @type {ProxyTableOutput}
     * @memberof SubscriptionUserResponse
     */
    proxySettings?: ProxyTableOutput;
    /**
     * 
     * @type {Expire}
     * @memberof SubscriptionUserResponse
     */
    expire?: Expire | null;
    /**
     * 
     * @type {number}
     * @memberof SubscriptionUserResponse
     */
    dataLimit?: number | null;
    /**
     * 
     * @type {DataLimitResetStrategy}
     * @memberof SubscriptionUserResponse
     */
    dataLimitResetStrategy?: DataLimitResetStrategy | null;
    /**
     * 
     * @type {number}
     * @memberof SubscriptionUserResponse
     */
    onHoldExpireDuration?: number | null;
    /**
     * 
     * @type {OnHoldTimeout}
     * @memberof SubscriptionUserResponse
     */
    onHoldTimeout?: OnHoldTimeout | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof SubscriptionUserResponse
     */
    groupIds?: Array<number> | null;
    /**
     * 
     * @type {NextPlanModel}
     * @memberof SubscriptionUserResponse
     */
    nextPlan?: NextPlanModel | null;
    /**
     * 
     * @type {number}
     * @memberof SubscriptionUserResponse
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionUserResponse
     */
    username: string;
    /**
     * 
     * @type {UserStatus}
     * @memberof SubscriptionUserResponse
     */
    status: UserStatus;
    /**
     * 
     * @type {number}
     * @memberof SubscriptionUserResponse
     */
    usedTraffic: number;
    /**
     * 
     * @type {number}
     * @memberof SubscriptionUserResponse
     */
    lifetimeUsedTraffic?: number;
    /**
     * 
     * @type {Date}
     * @memberof SubscriptionUserResponse
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof SubscriptionUserResponse
     */
    editAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof SubscriptionUserResponse
     */
    onlineAt?: Date | null;
}



/**
 * Check if a given object implements the SubscriptionUserResponse interface.
 */
export function instanceOfSubscriptionUserResponse(value: object): value is SubscriptionUserResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('usedTraffic' in value) || value['usedTraffic'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function SubscriptionUserResponseFromJSON(json: any): SubscriptionUserResponse {
    return SubscriptionUserResponseFromJSONTyped(json, false);
}

export function SubscriptionUserResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionUserResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'proxySettings': json['proxy_settings'] == null ? undefined : ProxyTableOutputFromJSON(json['proxy_settings']),
        'expire': json['expire'] == null ? undefined : ExpireFromJSON(json['expire']),
        'dataLimit': json['data_limit'] == null ? undefined : json['data_limit'],
        'dataLimitResetStrategy': json['data_limit_reset_strategy'] == null ? undefined : DataLimitResetStrategyFromJSON(json['data_limit_reset_strategy']),
        'onHoldExpireDuration': json['on_hold_expire_duration'] == null ? undefined : json['on_hold_expire_duration'],
        'onHoldTimeout': json['on_hold_timeout'] == null ? undefined : OnHoldTimeoutFromJSON(json['on_hold_timeout']),
        'groupIds': json['group_ids'] == null ? undefined : json['group_ids'],
        'nextPlan': json['next_plan'] == null ? undefined : NextPlanModelFromJSON(json['next_plan']),
        'id': json['id'],
        'username': json['username'],
        'status': UserStatusFromJSON(json['status']),
        'usedTraffic': json['used_traffic'],
        'lifetimeUsedTraffic': json['lifetime_used_traffic'] == null ? undefined : json['lifetime_used_traffic'],
        'createdAt': (new Date(json['created_at'])),
        'editAt': json['edit_at'] == null ? undefined : (new Date(json['edit_at'])),
        'onlineAt': json['online_at'] == null ? undefined : (new Date(json['online_at'])),
    };
}

export function SubscriptionUserResponseToJSON(json: any): SubscriptionUserResponse {
    return SubscriptionUserResponseToJSONTyped(json, false);
}

export function SubscriptionUserResponseToJSONTyped(value?: SubscriptionUserResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'proxy_settings': ProxyTableOutputToJSON(value['proxySettings']),
        'expire': ExpireToJSON(value['expire']),
        'data_limit': value['dataLimit'],
        'data_limit_reset_strategy': DataLimitResetStrategyToJSON(value['dataLimitResetStrategy']),
        'on_hold_expire_duration': value['onHoldExpireDuration'],
        'on_hold_timeout': OnHoldTimeoutToJSON(value['onHoldTimeout']),
        'group_ids': value['groupIds'],
        'next_plan': NextPlanModelToJSON(value['nextPlan']),
        'id': value['id'],
        'username': value['username'],
        'status': UserStatusToJSON(value['status']),
        'used_traffic': value['usedTraffic'],
        'lifetime_used_traffic': value['lifetimeUsedTraffic'],
        'created_at': ((value['createdAt']).toISOString()),
        'edit_at': value['editAt'] == null ? undefined : ((value['editAt'] as any).toISOString()),
        'online_at': value['onlineAt'] == null ? undefined : ((value['onlineAt'] as any).toISOString()),
    };
}

