/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution Powered by Xray
 *
 * The version of the OpenAPI document: 0.8.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SystemStats
 */
export interface SystemStats {
    /**
     * 
     * @type {string}
     * @memberof SystemStats
     */
    'version': string;
    /**
     * 
     * @type {number}
     * @memberof SystemStats
     */
    'mem_total': number;
    /**
     * 
     * @type {number}
     * @memberof SystemStats
     */
    'mem_used': number;
    /**
     * 
     * @type {number}
     * @memberof SystemStats
     */
    'cpu_cores': number;
    /**
     * 
     * @type {number}
     * @memberof SystemStats
     */
    'cpu_usage': number;
    /**
     * 
     * @type {number}
     * @memberof SystemStats
     */
    'total_user': number;
    /**
     * 
     * @type {number}
     * @memberof SystemStats
     */
    'online_users': number;
    /**
     * 
     * @type {number}
     * @memberof SystemStats
     */
    'users_active': number;
    /**
     * 
     * @type {number}
     * @memberof SystemStats
     */
    'users_on_hold': number;
    /**
     * 
     * @type {number}
     * @memberof SystemStats
     */
    'users_disabled': number;
    /**
     * 
     * @type {number}
     * @memberof SystemStats
     */
    'users_expired': number;
    /**
     * 
     * @type {number}
     * @memberof SystemStats
     */
    'users_limited': number;
    /**
     * 
     * @type {number}
     * @memberof SystemStats
     */
    'incoming_bandwidth': number;
    /**
     * 
     * @type {number}
     * @memberof SystemStats
     */
    'outgoing_bandwidth': number;
    /**
     * 
     * @type {number}
     * @memberof SystemStats
     */
    'incoming_bandwidth_speed': number;
    /**
     * 
     * @type {number}
     * @memberof SystemStats
     */
    'outgoing_bandwidth_speed': number;
}

