/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HTTPRequest } from './HTTPRequest';
import {
    HTTPRequestFromJSON,
    HTTPRequestFromJSONTyped,
    HTTPRequestToJSON,
    HTTPRequestToJSONTyped,
} from './HTTPRequest';
import type { HTTPResponse } from './HTTPResponse';
import {
    HTTPResponseFromJSON,
    HTTPResponseFromJSONTyped,
    HTTPResponseToJSON,
    HTTPResponseToJSONTyped,
} from './HTTPResponse';

/**
 * 
 * @export
 * @interface TcpSettings
 */
export interface TcpSettings {
    /**
     * 
     * @type {string}
     * @memberof TcpSettings
     */
    header?: string;
    /**
     * 
     * @type {HTTPRequest}
     * @memberof TcpSettings
     */
    request?: HTTPRequest | null;
    /**
     * 
     * @type {HTTPResponse}
     * @memberof TcpSettings
     */
    response?: HTTPResponse | null;
}

/**
 * Check if a given object implements the TcpSettings interface.
 */
export function instanceOfTcpSettings(value: object): value is TcpSettings {
    return true;
}

export function TcpSettingsFromJSON(json: any): TcpSettings {
    return TcpSettingsFromJSONTyped(json, false);
}

export function TcpSettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): TcpSettings {
    if (json == null) {
        return json;
    }
    return {
        
        'header': json['header'] == null ? undefined : json['header'],
        'request': json['request'] == null ? undefined : HTTPRequestFromJSON(json['request']),
        'response': json['response'] == null ? undefined : HTTPResponseFromJSON(json['response']),
    };
}

export function TcpSettingsToJSON(json: any): TcpSettings {
    return TcpSettingsToJSONTyped(json, false);
}

export function TcpSettingsToJSONTyped(value?: TcpSettings | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'header': value['header'],
        'request': HTTPRequestToJSON(value['request']),
        'response': HTTPResponseToJSON(value['response']),
    };
}

