/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RunMethod } from './run-method';

/**
 * 
 * @export
 * @interface Telegram
 */
export interface Telegram {
    /**
     * 
     * @type {boolean}
     * @memberof Telegram
     */
    'enable'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Telegram
     */
    'token'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Telegram
     */
    'webhook_url'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Telegram
     */
    'webhook_secret'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Telegram
     */
    'proxy_url'?: string | null;
    /**
     * 
     * @type {RunMethod}
     * @memberof Telegram
     */
    'method'?: RunMethod;
    /**
     * 
     * @type {boolean}
     * @memberof Telegram
     */
    'mini_app_login'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Telegram
     */
    'mini_app_web_url'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof Telegram
     */
    'for_admins_only'?: boolean;
}



