/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { XHttpSettingsOutput } from './XHttpSettingsOutput';
import {
    XHttpSettingsOutputFromJSON,
    XHttpSettingsOutputFromJSONTyped,
    XHttpSettingsOutputToJSON,
    XHttpSettingsOutputToJSONTyped,
} from './XHttpSettingsOutput';
import type { KCPSettings } from './KCPSettings';
import {
    KCPSettingsFromJSON,
    KCPSettingsFromJSONTyped,
    KCPSettingsToJSON,
    KCPSettingsToJSONTyped,
} from './KCPSettings';
import type { WebSocketSettings } from './WebSocketSettings';
import {
    WebSocketSettingsFromJSON,
    WebSocketSettingsFromJSONTyped,
    WebSocketSettingsToJSON,
    WebSocketSettingsToJSONTyped,
} from './WebSocketSettings';
import type { TcpSettings } from './TcpSettings';
import {
    TcpSettingsFromJSON,
    TcpSettingsFromJSONTyped,
    TcpSettingsToJSON,
    TcpSettingsToJSONTyped,
} from './TcpSettings';
import type { GRPCSettings } from './GRPCSettings';
import {
    GRPCSettingsFromJSON,
    GRPCSettingsFromJSONTyped,
    GRPCSettingsToJSON,
    GRPCSettingsToJSONTyped,
} from './GRPCSettings';

/**
 * 
 * @export
 * @interface TransportSettingsOutput
 */
export interface TransportSettingsOutput {
    /**
     * 
     * @type {XHttpSettingsOutput}
     * @memberof TransportSettingsOutput
     */
    xhttpSettings?: XHttpSettingsOutput | null;
    /**
     * 
     * @type {GRPCSettings}
     * @memberof TransportSettingsOutput
     */
    grpcSettings?: GRPCSettings | null;
    /**
     * 
     * @type {KCPSettings}
     * @memberof TransportSettingsOutput
     */
    kcpSettings?: KCPSettings | null;
    /**
     * 
     * @type {TcpSettings}
     * @memberof TransportSettingsOutput
     */
    tcpSettings?: TcpSettings | null;
    /**
     * 
     * @type {WebSocketSettings}
     * @memberof TransportSettingsOutput
     */
    websocketSettings?: WebSocketSettings | null;
}

/**
 * Check if a given object implements the TransportSettingsOutput interface.
 */
export function instanceOfTransportSettingsOutput(value: object): value is TransportSettingsOutput {
    return true;
}

export function TransportSettingsOutputFromJSON(json: any): TransportSettingsOutput {
    return TransportSettingsOutputFromJSONTyped(json, false);
}

export function TransportSettingsOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransportSettingsOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'xhttpSettings': json['xhttp_settings'] == null ? undefined : XHttpSettingsOutputFromJSON(json['xhttp_settings']),
        'grpcSettings': json['grpc_settings'] == null ? undefined : GRPCSettingsFromJSON(json['grpc_settings']),
        'kcpSettings': json['kcp_settings'] == null ? undefined : KCPSettingsFromJSON(json['kcp_settings']),
        'tcpSettings': json['tcp_settings'] == null ? undefined : TcpSettingsFromJSON(json['tcp_settings']),
        'websocketSettings': json['websocket_settings'] == null ? undefined : WebSocketSettingsFromJSON(json['websocket_settings']),
    };
}

export function TransportSettingsOutputToJSON(json: any): TransportSettingsOutput {
    return TransportSettingsOutputToJSONTyped(json, false);
}

export function TransportSettingsOutputToJSONTyped(value?: TransportSettingsOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'xhttp_settings': XHttpSettingsOutputToJSON(value['xhttpSettings']),
        'grpc_settings': GRPCSettingsToJSON(value['grpcSettings']),
        'kcp_settings': KCPSettingsToJSON(value['kcpSettings']),
        'tcp_settings': TcpSettingsToJSON(value['tcpSettings']),
        'websocket_settings': WebSocketSettingsToJSON(value['websocketSettings']),
    };
}

