/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GRPCSettings } from './grpcsettings';
// May contain unused imports in some cases
// @ts-ignore
import type { KCPSettings } from './kcpsettings';
// May contain unused imports in some cases
// @ts-ignore
import type { TcpSettings } from './tcp-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { WebSocketSettings } from './web-socket-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { XHttpSettingsInput } from './xhttp-settings-input';

/**
 * 
 * @export
 * @interface TransportSettingsInput
 */
export interface TransportSettingsInput {
    /**
     * 
     * @type {XHttpSettingsInput}
     * @memberof TransportSettingsInput
     */
    'xhttp_settings'?: XHttpSettingsInput | null;
    /**
     * 
     * @type {GRPCSettings}
     * @memberof TransportSettingsInput
     */
    'grpc_settings'?: GRPCSettings | null;
    /**
     * 
     * @type {KCPSettings}
     * @memberof TransportSettingsInput
     */
    'kcp_settings'?: KCPSettings | null;
    /**
     * 
     * @type {TcpSettings}
     * @memberof TransportSettingsInput
     */
    'tcp_settings'?: TcpSettings | null;
    /**
     * 
     * @type {WebSocketSettings}
     * @memberof TransportSettingsInput
     */
    'websocket_settings'?: WebSocketSettings | null;
}

