/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TrojanSettings
 */
export interface TrojanSettings {
    /**
     * 
     * @type {string}
     * @memberof TrojanSettings
     */
    password?: string;
}

/**
 * Check if a given object implements the TrojanSettings interface.
 */
export function instanceOfTrojanSettings(value: object): value is TrojanSettings {
    return true;
}

export function TrojanSettingsFromJSON(json: any): TrojanSettings {
    return TrojanSettingsFromJSONTyped(json, false);
}

export function TrojanSettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrojanSettings {
    if (json == null) {
        return json;
    }
    return {
        
        'password': json['password'] == null ? undefined : json['password'],
    };
}

export function TrojanSettingsToJSON(json: any): TrojanSettings {
    return TrojanSettingsToJSONTyped(json, false);
}

export function TrojanSettingsToJSONTyped(value?: TrojanSettings | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'password': value['password'],
    };
}

