/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DataLimitResetStrategy } from './data-limit-reset-strategy';
// May contain unused imports in some cases
// @ts-ignore
import type { Expire } from './expire';
// May contain unused imports in some cases
// @ts-ignore
import type { NextPlanModel } from './next-plan-model';
// May contain unused imports in some cases
// @ts-ignore
import type { OnHoldTimeout } from './on-hold-timeout';
// May contain unused imports in some cases
// @ts-ignore
import type { ProxyTableInput } from './proxy-table-input';
// May contain unused imports in some cases
// @ts-ignore
import type { UserStatusCreate } from './user-status-create';

/**
 * 
 * @export
 * @interface UserCreate
 */
export interface UserCreate {
    /**
     * 
     * @type {ProxyTableInput}
     * @memberof UserCreate
     */
    'proxy_settings'?: ProxyTableInput;
    /**
     * 
     * @type {Expire}
     * @memberof UserCreate
     */
    'expire'?: Expire | null;
    /**
     * 
     * @type {number}
     * @memberof UserCreate
     */
    'data_limit'?: number | null;
    /**
     * 
     * @type {DataLimitResetStrategy}
     * @memberof UserCreate
     */
    'data_limit_reset_strategy'?: DataLimitResetStrategy | null;
    /**
     * 
     * @type {string}
     * @memberof UserCreate
     */
    'note'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof UserCreate
     */
    'on_hold_expire_duration'?: number | null;
    /**
     * 
     * @type {OnHoldTimeout}
     * @memberof UserCreate
     */
    'on_hold_timeout'?: OnHoldTimeout | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof UserCreate
     */
    'group_ids'?: Array<number> | null;
    /**
     * 
     * @type {number}
     * @memberof UserCreate
     */
    'auto_delete_in_days'?: number | null;
    /**
     * 
     * @type {NextPlanModel}
     * @memberof UserCreate
     */
    'next_plan'?: NextPlanModel | null;
    /**
     * 
     * @type {string}
     * @memberof UserCreate
     */
    'username': string;
    /**
     * 
     * @type {UserStatusCreate}
     * @memberof UserCreate
     */
    'status'?: UserStatusCreate | null;
}



