/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AdminBase } from './admin-base';
// May contain unused imports in some cases
// @ts-ignore
import type { DataLimitResetStrategy } from './data-limit-reset-strategy';
// May contain unused imports in some cases
// @ts-ignore
import type { Expire } from './expire';
// May contain unused imports in some cases
// @ts-ignore
import type { NextPlanModel } from './next-plan-model';
// May contain unused imports in some cases
// @ts-ignore
import type { OnHoldTimeout } from './on-hold-timeout';
// May contain unused imports in some cases
// @ts-ignore
import type { ProxyTableOutput } from './proxy-table-output';
// May contain unused imports in some cases
// @ts-ignore
import type { UserStatus } from './user-status';

/**
 * 
 * @export
 * @interface UserResponse
 */
export interface UserResponse {
    /**
     * 
     * @type {ProxyTableOutput}
     * @memberof UserResponse
     */
    'proxy_settings'?: ProxyTableOutput;
    /**
     * 
     * @type {Expire}
     * @memberof UserResponse
     */
    'expire'?: Expire | null;
    /**
     * 
     * @type {number}
     * @memberof UserResponse
     */
    'data_limit'?: number | null;
    /**
     * 
     * @type {DataLimitResetStrategy}
     * @memberof UserResponse
     */
    'data_limit_reset_strategy'?: DataLimitResetStrategy | null;
    /**
     * 
     * @type {string}
     * @memberof UserResponse
     */
    'note'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof UserResponse
     */
    'on_hold_expire_duration'?: number | null;
    /**
     * 
     * @type {OnHoldTimeout}
     * @memberof UserResponse
     */
    'on_hold_timeout'?: OnHoldTimeout | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof UserResponse
     */
    'group_ids'?: Array<number> | null;
    /**
     * 
     * @type {number}
     * @memberof UserResponse
     */
    'auto_delete_in_days'?: number | null;
    /**
     * 
     * @type {NextPlanModel}
     * @memberof UserResponse
     */
    'next_plan'?: NextPlanModel | null;
    /**
     * 
     * @type {number}
     * @memberof UserResponse
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof UserResponse
     */
    'username': string;
    /**
     * 
     * @type {UserStatus}
     * @memberof UserResponse
     */
    'status': UserStatus;
    /**
     * 
     * @type {number}
     * @memberof UserResponse
     */
    'used_traffic': number;
    /**
     * 
     * @type {number}
     * @memberof UserResponse
     */
    'lifetime_used_traffic'?: number;
    /**
     * 
     * @type {string}
     * @memberof UserResponse
     */
    'created_at': string;
    /**
     * 
     * @type {string}
     * @memberof UserResponse
     */
    'edit_at'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserResponse
     */
    'online_at'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserResponse
     */
    'subscription_url'?: string;
    /**
     * 
     * @type {AdminBase}
     * @memberof UserResponse
     */
    'admin'?: AdminBase | null;
}



