/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution Powered by Xray
 *
 * The version of the OpenAPI document: 0.8.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Admin } from './admin';
// May contain unused imports in some cases
// @ts-ignore
import type { NextPlanModel } from './next-plan-model';
// May contain unused imports in some cases
// @ts-ignore
import type { UserDataLimitResetStrategy } from './user-data-limit-reset-strategy';
// May contain unused imports in some cases
// @ts-ignore
import type { UserStatus } from './user-status';

/**
 * 
 * @export
 * @interface UserResponse
 */
export interface UserResponse {
    /**
     * 
     * @type {object}
     * @memberof UserResponse
     */
    'proxies': object;
    /**
     * 
     * @type {number}
     * @memberof UserResponse
     */
    'expire'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof UserResponse
     */
    'data_limit'?: number | null;
    /**
     * 
     * @type {UserDataLimitResetStrategy}
     * @memberof UserResponse
     */
    'data_limit_reset_strategy'?: UserDataLimitResetStrategy;
    /**
     * 
     * @type {{ [key: string]: Array<string>; }}
     * @memberof UserResponse
     */
    'inbounds'?: { [key: string]: Array<string>; };
    /**
     * 
     * @type {string}
     * @memberof UserResponse
     */
    'note'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserResponse
     */
    'sub_updated_at'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserResponse
     */
    'sub_last_user_agent'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserResponse
     */
    'online_at'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof UserResponse
     */
    'on_hold_expire_duration'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof UserResponse
     */
    'on_hold_timeout'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof UserResponse
     */
    'auto_delete_in_days'?: number | null;
    /**
     * 
     * @type {NextPlanModel}
     * @memberof UserResponse
     */
    'next_plan'?: NextPlanModel | null;
    /**
     * 
     * @type {string}
     * @memberof UserResponse
     */
    'username': string;
    /**
     * 
     * @type {UserStatus}
     * @memberof UserResponse
     */
    'status': UserStatus;
    /**
     * 
     * @type {number}
     * @memberof UserResponse
     */
    'used_traffic': number;
    /**
     * 
     * @type {number}
     * @memberof UserResponse
     */
    'lifetime_used_traffic'?: number;
    /**
     * 
     * @type {string}
     * @memberof UserResponse
     */
    'created_at': string;
    /**
     * 
     * @type {Array<string>}
     * @memberof UserResponse
     */
    'links'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof UserResponse
     */
    'subscription_url'?: string;
    /**
     * 
     * @type {{ [key: string]: Array<string>; }}
     * @memberof UserResponse
     */
    'excluded_inbounds'?: { [key: string]: Array<string>; };
    /**
     * 
     * @type {Admin}
     * @memberof UserResponse
     */
    'admin'?: Admin | null;
}



