/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DataLimitResetStrategy } from './data-limit-reset-strategy';
// May contain unused imports in some cases
// @ts-ignore
import type { ExtraSettings } from './extra-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { UserStatusCreate } from './user-status-create';

/**
 * 
 * @export
 * @interface UserTemplateModify
 */
export interface UserTemplateModify {
    /**
     * 
     * @type {string}
     * @memberof UserTemplateModify
     */
    'name'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof UserTemplateModify
     */
    'data_limit'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof UserTemplateModify
     */
    'expire_duration'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof UserTemplateModify
     */
    'username_prefix'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserTemplateModify
     */
    'username_suffix'?: string | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof UserTemplateModify
     */
    'group_ids'?: Array<number> | null;
    /**
     * 
     * @type {ExtraSettings}
     * @memberof UserTemplateModify
     */
    'extra_settings'?: ExtraSettings | null;
    /**
     * 
     * @type {UserStatusCreate}
     * @memberof UserTemplateModify
     */
    'status'?: UserStatusCreate | null;
    /**
     * 
     * @type {boolean}
     * @memberof UserTemplateModify
     */
    'reset_usages'?: boolean | null;
    /**
     * 
     * @type {number}
     * @memberof UserTemplateModify
     */
    'on_hold_timeout'?: number | null;
    /**
     * 
     * @type {DataLimitResetStrategy}
     * @memberof UserTemplateModify
     */
    'data_limit_reset_strategy'?: DataLimitResetStrategy;
    /**
     * 
     * @type {boolean}
     * @memberof UserTemplateModify
     */
    'is_disabled'?: boolean | null;
}



