/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserNotificationEnable
 */
export interface UserNotificationEnable {
    /**
     * 
     * @type {boolean}
     * @memberof UserNotificationEnable
     */
    create?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UserNotificationEnable
     */
    modify?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UserNotificationEnable
     */
    _delete?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UserNotificationEnable
     */
    statusChange?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UserNotificationEnable
     */
    resetDataUsage?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UserNotificationEnable
     */
    dataResetByNext?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UserNotificationEnable
     */
    subscriptionRevoked?: boolean;
}

/**
 * Check if a given object implements the UserNotificationEnable interface.
 */
export function instanceOfUserNotificationEnable(value: object): value is UserNotificationEnable {
    return true;
}

export function UserNotificationEnableFromJSON(json: any): UserNotificationEnable {
    return UserNotificationEnableFromJSONTyped(json, false);
}

export function UserNotificationEnableFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserNotificationEnable {
    if (json == null) {
        return json;
    }
    return {
        
        'create': json['create'] == null ? undefined : json['create'],
        'modify': json['modify'] == null ? undefined : json['modify'],
        '_delete': json['delete'] == null ? undefined : json['delete'],
        'statusChange': json['status_change'] == null ? undefined : json['status_change'],
        'resetDataUsage': json['reset_data_usage'] == null ? undefined : json['reset_data_usage'],
        'dataResetByNext': json['data_reset_by_next'] == null ? undefined : json['data_reset_by_next'],
        'subscriptionRevoked': json['subscription_revoked'] == null ? undefined : json['subscription_revoked'],
    };
}

export function UserNotificationEnableToJSON(json: any): UserNotificationEnable {
    return UserNotificationEnableToJSONTyped(json, false);
}

export function UserNotificationEnableToJSONTyped(value?: UserNotificationEnable | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'create': value['create'],
        'modify': value['modify'],
        'delete': value['_delete'],
        'status_change': value['statusChange'],
        'reset_data_usage': value['resetDataUsage'],
        'data_reset_by_next': value['dataResetByNext'],
        'subscription_revoked': value['subscriptionRevoked'],
    };
}

