/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { UserSubscriptionUpdateSchema } from './user-subscription-update-schema';

/**
 * 
 * @export
 * @interface UserSubscriptionUpdateList
 */
export interface UserSubscriptionUpdateList {
    /**
     * 
     * @type {Array<UserSubscriptionUpdateSchema>}
     * @memberof UserSubscriptionUpdateList
     */
    'updates'?: Array<UserSubscriptionUpdateSchema>;
    /**
     * 
     * @type {number}
     * @memberof UserSubscriptionUpdateList
     */
    'count': number;
}

