/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Period } from './Period';
import {
    PeriodFromJSON,
    PeriodFromJSONTyped,
    PeriodToJSON,
    PeriodToJSONTyped,
} from './Period';
import type { UserUsageStat } from './UserUsageStat';
import {
    UserUsageStatFromJSON,
    UserUsageStatFromJSONTyped,
    UserUsageStatToJSON,
    UserUsageStatToJSONTyped,
} from './UserUsageStat';

/**
 * 
 * @export
 * @interface UserUsageStatsList
 */
export interface UserUsageStatsList {
    /**
     * 
     * @type {Period}
     * @memberof UserUsageStatsList
     */
    period?: Period | null;
    /**
     * 
     * @type {Date}
     * @memberof UserUsageStatsList
     */
    start: Date;
    /**
     * 
     * @type {Date}
     * @memberof UserUsageStatsList
     */
    end: Date;
    /**
     * 
     * @type {{ [key: string]: Array<UserUsageStat>; }}
     * @memberof UserUsageStatsList
     */
    stats: { [key: string]: Array<UserUsageStat>; };
}



/**
 * Check if a given object implements the UserUsageStatsList interface.
 */
export function instanceOfUserUsageStatsList(value: object): value is UserUsageStatsList {
    if (!('start' in value) || value['start'] === undefined) return false;
    if (!('end' in value) || value['end'] === undefined) return false;
    if (!('stats' in value) || value['stats'] === undefined) return false;
    return true;
}

export function UserUsageStatsListFromJSON(json: any): UserUsageStatsList {
    return UserUsageStatsListFromJSONTyped(json, false);
}

export function UserUsageStatsListFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserUsageStatsList {
    if (json == null) {
        return json;
    }
    return {
        
        'period': json['period'] == null ? undefined : PeriodFromJSON(json['period']),
        'start': (new Date(json['start'])),
        'end': (new Date(json['end'])),
        'stats': json['stats'],
    };
}

export function UserUsageStatsListToJSON(json: any): UserUsageStatsList {
    return UserUsageStatsListToJSONTyped(json, false);
}

export function UserUsageStatsListToJSONTyped(value?: UserUsageStatsList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'period': PeriodToJSON(value['period']),
        'start': ((value['start']).toISOString()),
        'end': ((value['end']).toISOString()),
        'stats': value['stats'],
    };
}

