/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Period } from './period';
// May contain unused imports in some cases
// @ts-ignore
import type { UserUsageStat } from './user-usage-stat';

/**
 * 
 * @export
 * @interface UserUsageStatsList
 */
export interface UserUsageStatsList {
    /**
     * 
     * @type {Period}
     * @memberof UserUsageStatsList
     */
    'period'?: Period | null;
    /**
     * 
     * @type {string}
     * @memberof UserUsageStatsList
     */
    'start': string;
    /**
     * 
     * @type {string}
     * @memberof UserUsageStatsList
     */
    'end': string;
    /**
     * 
     * @type {{ [key: string]: Array<UserUsageStat>; }}
     * @memberof UserUsageStatsList
     */
    'stats': { [key: string]: Array<UserUsageStat>; };
}



