/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NodesValue } from './NodesValue';
import {
    NodesValueFromJSON,
    NodesValueFromJSONTyped,
    NodesValueToJSON,
    NodesValueToJSONTyped,
} from './NodesValue';

/**
 * User IP lists for all nodes
 * @export
 * @interface UserIPListAll
 */
export interface UserIPListAll {
    /**
     * 
     * @type {{ [key: string]: NodesValue; }}
     * @memberof UserIPListAll
     */
    nodes: { [key: string]: NodesValue; };
}

/**
 * Check if a given object implements the UserIPListAll interface.
 */
export function instanceOfUserIPListAll(value: object): value is UserIPListAll {
    if (!('nodes' in value) || value['nodes'] === undefined) return false;
    return true;
}

export function UserIPListAllFromJSON(json: any): UserIPListAll {
    return UserIPListAllFromJSONTyped(json, false);
}

export function UserIPListAllFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserIPListAll {
    if (json == null) {
        return json;
    }
    return {
        
        'nodes': (mapValues(json['nodes'], NodesValueFromJSON)),
    };
}

export function UserIPListAllToJSON(json: any): UserIPListAll {
    return UserIPListAllToJSONTyped(json, false);
}

export function UserIPListAllToJSONTyped(value?: UserIPListAll | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'nodes': (mapValues(value['nodes'], NodesValueToJSON)),
    };
}

