/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const UserStatusCreate = {
    Active: 'active',
    OnHold: 'on_hold'
} as const;
export type UserStatusCreate = typeof UserStatusCreate[keyof typeof UserStatusCreate];


export function instanceOfUserStatusCreate(value: any): boolean {
    for (const key in UserStatusCreate) {
        if (Object.prototype.hasOwnProperty.call(UserStatusCreate, key)) {
            if (UserStatusCreate[key as keyof typeof UserStatusCreate] === value) {
                return true;
            }
        }
    }
    return false;
}

export function UserStatusCreateFromJSON(json: any): UserStatusCreate {
    return UserStatusCreateFromJSONTyped(json, false);
}

export function UserStatusCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserStatusCreate {
    return json as UserStatusCreate;
}

export function UserStatusCreateToJSON(value?: UserStatusCreate | null): any {
    return value as any;
}

export function UserStatusCreateToJSONTyped(value: any, ignoreDiscriminator: boolean): UserStatusCreate {
    return value as UserStatusCreate;
}

