/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserStatusCreate } from './UserStatusCreate';
import {
    UserStatusCreateFromJSON,
    UserStatusCreateFromJSONTyped,
    UserStatusCreateToJSON,
    UserStatusCreateToJSONTyped,
} from './UserStatusCreate';
import type { DataLimitResetStrategy } from './DataLimitResetStrategy';
import {
    DataLimitResetStrategyFromJSON,
    DataLimitResetStrategyFromJSONTyped,
    DataLimitResetStrategyToJSON,
    DataLimitResetStrategyToJSONTyped,
} from './DataLimitResetStrategy';
import type { ExtraSettings } from './ExtraSettings';
import {
    ExtraSettingsFromJSON,
    ExtraSettingsFromJSONTyped,
    ExtraSettingsToJSON,
    ExtraSettingsToJSONTyped,
} from './ExtraSettings';

/**
 * 
 * @export
 * @interface UserTemplateCreate
 */
export interface UserTemplateCreate {
    /**
     * 
     * @type {string}
     * @memberof UserTemplateCreate
     */
    name?: string | null;
    /**
     * 
     * @type {number}
     * @memberof UserTemplateCreate
     */
    dataLimit?: number | null;
    /**
     * 
     * @type {number}
     * @memberof UserTemplateCreate
     */
    expireDuration?: number | null;
    /**
     * 
     * @type {string}
     * @memberof UserTemplateCreate
     */
    usernamePrefix?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserTemplateCreate
     */
    usernameSuffix?: string | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof UserTemplateCreate
     */
    groupIds: Array<number>;
    /**
     * 
     * @type {ExtraSettings}
     * @memberof UserTemplateCreate
     */
    extraSettings?: ExtraSettings | null;
    /**
     * 
     * @type {UserStatusCreate}
     * @memberof UserTemplateCreate
     */
    status?: UserStatusCreate | null;
    /**
     * 
     * @type {boolean}
     * @memberof UserTemplateCreate
     */
    resetUsages?: boolean | null;
    /**
     * 
     * @type {number}
     * @memberof UserTemplateCreate
     */
    onHoldTimeout?: number | null;
    /**
     * 
     * @type {DataLimitResetStrategy}
     * @memberof UserTemplateCreate
     */
    dataLimitResetStrategy?: DataLimitResetStrategy;
    /**
     * 
     * @type {boolean}
     * @memberof UserTemplateCreate
     */
    isDisabled?: boolean | null;
}



/**
 * Check if a given object implements the UserTemplateCreate interface.
 */
export function instanceOfUserTemplateCreate(value: object): value is UserTemplateCreate {
    if (!('groupIds' in value) || value['groupIds'] === undefined) return false;
    return true;
}

export function UserTemplateCreateFromJSON(json: any): UserTemplateCreate {
    return UserTemplateCreateFromJSONTyped(json, false);
}

export function UserTemplateCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserTemplateCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'dataLimit': json['data_limit'] == null ? undefined : json['data_limit'],
        'expireDuration': json['expire_duration'] == null ? undefined : json['expire_duration'],
        'usernamePrefix': json['username_prefix'] == null ? undefined : json['username_prefix'],
        'usernameSuffix': json['username_suffix'] == null ? undefined : json['username_suffix'],
        'groupIds': json['group_ids'],
        'extraSettings': json['extra_settings'] == null ? undefined : ExtraSettingsFromJSON(json['extra_settings']),
        'status': json['status'] == null ? undefined : UserStatusCreateFromJSON(json['status']),
        'resetUsages': json['reset_usages'] == null ? undefined : json['reset_usages'],
        'onHoldTimeout': json['on_hold_timeout'] == null ? undefined : json['on_hold_timeout'],
        'dataLimitResetStrategy': json['data_limit_reset_strategy'] == null ? undefined : DataLimitResetStrategyFromJSON(json['data_limit_reset_strategy']),
        'isDisabled': json['is_disabled'] == null ? undefined : json['is_disabled'],
    };
}

export function UserTemplateCreateToJSON(json: any): UserTemplateCreate {
    return UserTemplateCreateToJSONTyped(json, false);
}

export function UserTemplateCreateToJSONTyped(value?: UserTemplateCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'data_limit': value['dataLimit'],
        'expire_duration': value['expireDuration'],
        'username_prefix': value['usernamePrefix'],
        'username_suffix': value['usernameSuffix'],
        'group_ids': value['groupIds'],
        'extra_settings': ExtraSettingsToJSON(value['extraSettings']),
        'status': UserStatusCreateToJSON(value['status']),
        'reset_usages': value['resetUsages'],
        'on_hold_timeout': value['onHoldTimeout'],
        'data_limit_reset_strategy': DataLimitResetStrategyToJSON(value['dataLimitResetStrategy']),
        'is_disabled': value['isDisabled'],
    };
}

