/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution Powered by Xray
 *
 * The version of the OpenAPI document: 0.8.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UserUsageResponse
 */
export interface UserUsageResponse {
    /**
     * 
     * @type {number}
     * @memberof UserUsageResponse
     */
    'node_id'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof UserUsageResponse
     */
    'node_name': string;
    /**
     * 
     * @type {number}
     * @memberof UserUsageResponse
     */
    'used_traffic': number;
}

