/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution Powered by Xray
 *
 * The version of the OpenAPI document: 0.8.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { NextPlanModel } from './next-plan-model';
// May contain unused imports in some cases
// @ts-ignore
import type { UserDataLimitResetStrategy } from './user-data-limit-reset-strategy';
// May contain unused imports in some cases
// @ts-ignore
import type { UserStatusCreate } from './user-status-create';

/**
 * 
 * @export
 * @interface UserCreate
 */
export interface UserCreate {
    /**
     * 
     * @type {{ [key: string]: object; }}
     * @memberof UserCreate
     */
    'proxies'?: { [key: string]: object; };
    /**
     * 
     * @type {number}
     * @memberof UserCreate
     */
    'expire'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof UserCreate
     */
    'data_limit'?: number | null;
    /**
     * 
     * @type {UserDataLimitResetStrategy}
     * @memberof UserCreate
     */
    'data_limit_reset_strategy'?: UserDataLimitResetStrategy;
    /**
     * 
     * @type {{ [key: string]: Array<string>; }}
     * @memberof UserCreate
     */
    'inbounds'?: { [key: string]: Array<string>; };
    /**
     * 
     * @type {string}
     * @memberof UserCreate
     */
    'note'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserCreate
     */
    'sub_updated_at'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserCreate
     */
    'sub_last_user_agent'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserCreate
     */
    'online_at'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof UserCreate
     */
    'on_hold_expire_duration'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof UserCreate
     */
    'on_hold_timeout'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof UserCreate
     */
    'auto_delete_in_days'?: number | null;
    /**
     * 
     * @type {NextPlanModel}
     * @memberof UserCreate
     */
    'next_plan'?: NextPlanModel | null;
    /**
     * 
     * @type {string}
     * @memberof UserCreate
     */
    'username': string;
    /**
     * 
     * @type {UserStatusCreate}
     * @memberof UserCreate
     */
    'status'?: UserStatusCreate;
}



