/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserSubscriptionUpdateSchema } from './UserSubscriptionUpdateSchema';
import {
    UserSubscriptionUpdateSchemaFromJSON,
    UserSubscriptionUpdateSchemaFromJSONTyped,
    UserSubscriptionUpdateSchemaToJSON,
    UserSubscriptionUpdateSchemaToJSONTyped,
} from './UserSubscriptionUpdateSchema';

/**
 * 
 * @export
 * @interface UserSubscriptionUpdateList
 */
export interface UserSubscriptionUpdateList {
    /**
     * 
     * @type {Array<UserSubscriptionUpdateSchema>}
     * @memberof UserSubscriptionUpdateList
     */
    updates?: Array<UserSubscriptionUpdateSchema>;
    /**
     * 
     * @type {number}
     * @memberof UserSubscriptionUpdateList
     */
    count: number;
}

/**
 * Check if a given object implements the UserSubscriptionUpdateList interface.
 */
export function instanceOfUserSubscriptionUpdateList(value: object): value is UserSubscriptionUpdateList {
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function UserSubscriptionUpdateListFromJSON(json: any): UserSubscriptionUpdateList {
    return UserSubscriptionUpdateListFromJSONTyped(json, false);
}

export function UserSubscriptionUpdateListFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserSubscriptionUpdateList {
    if (json == null) {
        return json;
    }
    return {
        
        'updates': json['updates'] == null ? undefined : ((json['updates'] as Array<any>).map(UserSubscriptionUpdateSchemaFromJSON)),
        'count': json['count'],
    };
}

export function UserSubscriptionUpdateListToJSON(json: any): UserSubscriptionUpdateList {
    return UserSubscriptionUpdateListToJSONTyped(json, false);
}

export function UserSubscriptionUpdateListToJSONTyped(value?: UserSubscriptionUpdateList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'updates': value['updates'] == null ? undefined : ((value['updates'] as Array<any>).map(UserSubscriptionUpdateSchemaToJSON)),
        'count': value['count'],
    };
}

