/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const UsernameGenerationStrategy = {
    Random: 'random',
    Sequence: 'sequence'
} as const;
export type UsernameGenerationStrategy = typeof UsernameGenerationStrategy[keyof typeof UsernameGenerationStrategy];


export function instanceOfUsernameGenerationStrategy(value: any): boolean {
    for (const key in UsernameGenerationStrategy) {
        if (Object.prototype.hasOwnProperty.call(UsernameGenerationStrategy, key)) {
            if (UsernameGenerationStrategy[key as keyof typeof UsernameGenerationStrategy] === value) {
                return true;
            }
        }
    }
    return false;
}

export function UsernameGenerationStrategyFromJSON(json: any): UsernameGenerationStrategy {
    return UsernameGenerationStrategyFromJSONTyped(json, false);
}

export function UsernameGenerationStrategyFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsernameGenerationStrategy {
    return json as UsernameGenerationStrategy;
}

export function UsernameGenerationStrategyToJSON(value?: UsernameGenerationStrategy | null): any {
    return value as any;
}

export function UsernameGenerationStrategyToJSONTyped(value: any, ignoreDiscriminator: boolean): UsernameGenerationStrategy {
    return value as UsernameGenerationStrategy;
}

