/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebhookInfo
 */
export interface WebhookInfo {
    /**
     * 
     * @type {string}
     * @memberof WebhookInfo
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof WebhookInfo
     */
    secret: string;
}

/**
 * Check if a given object implements the WebhookInfo interface.
 */
export function instanceOfWebhookInfo(value: object): value is WebhookInfo {
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('secret' in value) || value['secret'] === undefined) return false;
    return true;
}

export function WebhookInfoFromJSON(json: any): WebhookInfo {
    return WebhookInfoFromJSONTyped(json, false);
}

export function WebhookInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
        'secret': json['secret'],
    };
}

export function WebhookInfoToJSON(json: any): WebhookInfo {
    return WebhookInfoToJSONTyped(json, false);
}

export function WebhookInfoToJSONTyped(value?: WebhookInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
        'secret': value['secret'],
    };
}

