/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebSocketSettings
 */
export interface WebSocketSettings {
    /**
     * 
     * @type {number}
     * @memberof WebSocketSettings
     */
    heartbeatPeriod?: number | null;
}

/**
 * Check if a given object implements the WebSocketSettings interface.
 */
export function instanceOfWebSocketSettings(value: object): value is WebSocketSettings {
    return true;
}

export function WebSocketSettingsFromJSON(json: any): WebSocketSettings {
    return WebSocketSettingsFromJSONTyped(json, false);
}

export function WebSocketSettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebSocketSettings {
    if (json == null) {
        return json;
    }
    return {
        
        'heartbeatPeriod': json['heartbeatPeriod'] == null ? undefined : json['heartbeatPeriod'],
    };
}

export function WebSocketSettingsToJSON(json: any): WebSocketSettings {
    return WebSocketSettingsToJSONTyped(json, false);
}

export function WebSocketSettingsToJSONTyped(value?: WebSocketSettings | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'heartbeatPeriod': value['heartbeatPeriod'],
    };
}

