/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const XHttpModes = {
    Auto: 'auto',
    PacketUp: 'packet-up',
    StreamUp: 'stream-up',
    StreamOne: 'stream-one'
} as const;
export type XHttpModes = typeof XHttpModes[keyof typeof XHttpModes];


export function instanceOfXHttpModes(value: any): boolean {
    for (const key in XHttpModes) {
        if (Object.prototype.hasOwnProperty.call(XHttpModes, key)) {
            if (XHttpModes[key as keyof typeof XHttpModes] === value) {
                return true;
            }
        }
    }
    return false;
}

export function XHttpModesFromJSON(json: any): XHttpModes {
    return XHttpModesFromJSONTyped(json, false);
}

export function XHttpModesFromJSONTyped(json: any, ignoreDiscriminator: boolean): XHttpModes {
    return json as XHttpModes;
}

export function XHttpModesToJSON(value?: XHttpModes | null): any {
    return value as any;
}

export function XHttpModesToJSONTyped(value: any, ignoreDiscriminator: boolean): XHttpModes {
    return value as XHttpModes;
}

