/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ScMaxEachPostBytes } from './sc-max-each-post-bytes';
// May contain unused imports in some cases
// @ts-ignore
import type { ScMinPostsIntervalMs } from './sc-min-posts-interval-ms';
// May contain unused imports in some cases
// @ts-ignore
import type { XHttpModes } from './xhttp-modes';
// May contain unused imports in some cases
// @ts-ignore
import type { XMuxSettingsInput } from './xmux-settings-input';
// May contain unused imports in some cases
// @ts-ignore
import type { XPaddingBytes } from './xpadding-bytes';

/**
 * 
 * @export
 * @interface XHttpSettingsInput
 */
export interface XHttpSettingsInput {
    /**
     * 
     * @type {XHttpModes}
     * @memberof XHttpSettingsInput
     */
    'mode'?: XHttpModes;
    /**
     * 
     * @type {boolean}
     * @memberof XHttpSettingsInput
     */
    'no_grpc_header'?: boolean | null;
    /**
     * 
     * @type {XPaddingBytes}
     * @memberof XHttpSettingsInput
     */
    'x_padding_bytes'?: XPaddingBytes | null;
    /**
     * 
     * @type {ScMaxEachPostBytes}
     * @memberof XHttpSettingsInput
     */
    'sc_max_each_post_bytes'?: ScMaxEachPostBytes | null;
    /**
     * 
     * @type {ScMinPostsIntervalMs}
     * @memberof XHttpSettingsInput
     */
    'sc_min_posts_interval_ms'?: ScMinPostsIntervalMs | null;
    /**
     * 
     * @type {XMuxSettingsInput}
     * @memberof XHttpSettingsInput
     */
    'xmux'?: XMuxSettingsInput | null;
    /**
     * 
     * @type {number}
     * @memberof XHttpSettingsInput
     */
    'download_settings'?: number | null;
}



