/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HMaxRequestTimes } from './HMaxRequestTimes';
import {
    HMaxRequestTimesFromJSON,
    HMaxRequestTimesFromJSONTyped,
    HMaxRequestTimesToJSON,
    HMaxRequestTimesToJSONTyped,
} from './HMaxRequestTimes';
import type { MaxConnections } from './MaxConnections';
import {
    MaxConnectionsFromJSON,
    MaxConnectionsFromJSONTyped,
    MaxConnectionsToJSON,
    MaxConnectionsToJSONTyped,
} from './MaxConnections';
import type { MaxConcurrency } from './MaxConcurrency';
import {
    MaxConcurrencyFromJSON,
    MaxConcurrencyFromJSONTyped,
    MaxConcurrencyToJSON,
    MaxConcurrencyToJSONTyped,
} from './MaxConcurrency';
import type { HMaxReusableSecs } from './HMaxReusableSecs';
import {
    HMaxReusableSecsFromJSON,
    HMaxReusableSecsFromJSONTyped,
    HMaxReusableSecsToJSON,
    HMaxReusableSecsToJSONTyped,
} from './HMaxReusableSecs';
import type { CMaxReuseTimes } from './CMaxReuseTimes';
import {
    CMaxReuseTimesFromJSON,
    CMaxReuseTimesFromJSONTyped,
    CMaxReuseTimesToJSON,
    CMaxReuseTimesToJSONTyped,
} from './CMaxReuseTimes';

/**
 * 
 * @export
 * @interface XMuxSettingsInput
 */
export interface XMuxSettingsInput {
    /**
     * 
     * @type {MaxConcurrency}
     * @memberof XMuxSettingsInput
     */
    maxConcurrency?: MaxConcurrency | null;
    /**
     * 
     * @type {MaxConnections}
     * @memberof XMuxSettingsInput
     */
    maxConnections?: MaxConnections | null;
    /**
     * 
     * @type {CMaxReuseTimes}
     * @memberof XMuxSettingsInput
     */
    cMaxReuseTimes?: CMaxReuseTimes | null;
    /**
     * 
     * @type {HMaxReusableSecs}
     * @memberof XMuxSettingsInput
     */
    hMaxReusableSecs?: HMaxReusableSecs | null;
    /**
     * 
     * @type {HMaxRequestTimes}
     * @memberof XMuxSettingsInput
     */
    hMaxRequestTimes?: HMaxRequestTimes | null;
    /**
     * 
     * @type {number}
     * @memberof XMuxSettingsInput
     */
    hKeepAlivePeriod?: number | null;
}

/**
 * Check if a given object implements the XMuxSettingsInput interface.
 */
export function instanceOfXMuxSettingsInput(value: object): value is XMuxSettingsInput {
    return true;
}

export function XMuxSettingsInputFromJSON(json: any): XMuxSettingsInput {
    return XMuxSettingsInputFromJSONTyped(json, false);
}

export function XMuxSettingsInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): XMuxSettingsInput {
    if (json == null) {
        return json;
    }
    return {
        
        'maxConcurrency': json['max_concurrency'] == null ? undefined : MaxConcurrencyFromJSON(json['max_concurrency']),
        'maxConnections': json['max_connections'] == null ? undefined : MaxConnectionsFromJSON(json['max_connections']),
        'cMaxReuseTimes': json['c_max_reuse_times'] == null ? undefined : CMaxReuseTimesFromJSON(json['c_max_reuse_times']),
        'hMaxReusableSecs': json['h_max_reusable_secs'] == null ? undefined : HMaxReusableSecsFromJSON(json['h_max_reusable_secs']),
        'hMaxRequestTimes': json['h_max_request_times'] == null ? undefined : HMaxRequestTimesFromJSON(json['h_max_request_times']),
        'hKeepAlivePeriod': json['h_keep_alive_period'] == null ? undefined : json['h_keep_alive_period'],
    };
}

export function XMuxSettingsInputToJSON(json: any): XMuxSettingsInput {
    return XMuxSettingsInputToJSONTyped(json, false);
}

export function XMuxSettingsInputToJSONTyped(value?: XMuxSettingsInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'max_concurrency': MaxConcurrencyToJSON(value['maxConcurrency']),
        'max_connections': MaxConnectionsToJSON(value['maxConnections']),
        'c_max_reuse_times': CMaxReuseTimesToJSON(value['cMaxReuseTimes']),
        'h_max_reusable_secs': HMaxReusableSecsToJSON(value['hMaxReusableSecs']),
        'h_max_request_times': HMaxRequestTimesToJSON(value['hMaxRequestTimes']),
        'h_keep_alive_period': value['hKeepAlivePeriod'],
    };
}

