/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface XrayFragmentSettings
 */
export interface XrayFragmentSettings {
    /**
     * 
     * @type {string}
     * @memberof XrayFragmentSettings
     */
    packets: string;
    /**
     * 
     * @type {string}
     * @memberof XrayFragmentSettings
     */
    length: string;
    /**
     * 
     * @type {string}
     * @memberof XrayFragmentSettings
     */
    interval: string;
}

/**
 * Check if a given object implements the XrayFragmentSettings interface.
 */
export function instanceOfXrayFragmentSettings(value: object): value is XrayFragmentSettings {
    if (!('packets' in value) || value['packets'] === undefined) return false;
    if (!('length' in value) || value['length'] === undefined) return false;
    if (!('interval' in value) || value['interval'] === undefined) return false;
    return true;
}

export function XrayFragmentSettingsFromJSON(json: any): XrayFragmentSettings {
    return XrayFragmentSettingsFromJSONTyped(json, false);
}

export function XrayFragmentSettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): XrayFragmentSettings {
    if (json == null) {
        return json;
    }
    return {
        
        'packets': json['packets'],
        'length': json['length'],
        'interval': json['interval'],
    };
}

export function XrayFragmentSettingsToJSON(json: any): XrayFragmentSettings {
    return XrayFragmentSettingsToJSONTyped(json, false);
}

export function XrayFragmentSettingsToJSONTyped(value?: XrayFragmentSettings | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'packets': value['packets'],
        'length': value['length'],
        'interval': value['interval'],
    };
}

