/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface XrayNoiseSettings
 */
export interface XrayNoiseSettings {
    /**
     * 
     * @type {string}
     * @memberof XrayNoiseSettings
     */
    'type': string;
    /**
     * 
     * @type {string}
     * @memberof XrayNoiseSettings
     */
    'packet': string;
    /**
     * 
     * @type {string}
     * @memberof XrayNoiseSettings
     */
    'delay': string;
    /**
     * 
     * @type {string}
     * @memberof XrayNoiseSettings
     */
    'apply_to'?: string;
}

