/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const XTLSFlows = {
    Empty: '',
    XtlsRprxVision: 'xtls-rprx-vision'
} as const;

export type XTLSFlows = typeof XTLSFlows[keyof typeof XTLSFlows];



