/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CoreCreate } from '../models';
// @ts-ignore
import type { CoreResponse } from '../models';
// @ts-ignore
import type { CoreResponseList } from '../models';
// @ts-ignore
import type { Forbidden } from '../models';
// @ts-ignore
import type { HTTPValidationError } from '../models';
// @ts-ignore
import type { Unauthorized } from '../models';
/**
 * CoreApi - axios parameter creator
 * @export
 */
export const CoreApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Create a new core configuration.
         * @summary Create Core Config
         * @param {CoreCreate} coreCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createCoreConfig: async (coreCreate: CoreCreate, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'coreCreate' is not null or undefined
            assertParamExists('createCoreConfig', 'coreCreate', coreCreate)
            const localVarPath = `/api/core`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(coreCreate, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Delete a core configuration.
         * @summary Delete Core Config
         * @param {number} coreId 
         * @param {boolean} [restartNodes] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteCoreConfig: async (coreId: number, restartNodes?: boolean, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'coreId' is not null or undefined
            assertParamExists('deleteCoreConfig', 'coreId', coreId)
            const localVarPath = `/api/core/{core_id}`
                .replace(`{${"core_id"}}`, encodeURIComponent(String(coreId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)

            if (restartNodes !== undefined) {
                localVarQueryParameter['restart_nodes'] = restartNodes;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get a list of all core configurations.
         * @summary Get All Cores
         * @param {number | null} [offset] 
         * @param {number | null} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllCores: async (offset?: number | null, limit?: number | null, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/cores`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get a core configuration by its ID.
         * @summary Get Core Config
         * @param {number} coreId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCoreConfig: async (coreId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'coreId' is not null or undefined
            assertParamExists('getCoreConfig', 'coreId', coreId)
            const localVarPath = `/api/core/{core_id}`
                .replace(`{${"core_id"}}`, encodeURIComponent(String(coreId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Update an existing core configuration.
         * @summary Modify Core Config
         * @param {number} coreId 
         * @param {boolean} restartNodes 
         * @param {CoreCreate} coreCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        modifyCoreConfig: async (coreId: number, restartNodes: boolean, coreCreate: CoreCreate, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'coreId' is not null or undefined
            assertParamExists('modifyCoreConfig', 'coreId', coreId)
            // verify required parameter 'restartNodes' is not null or undefined
            assertParamExists('modifyCoreConfig', 'restartNodes', restartNodes)
            // verify required parameter 'coreCreate' is not null or undefined
            assertParamExists('modifyCoreConfig', 'coreCreate', coreCreate)
            const localVarPath = `/api/core/{core_id}`
                .replace(`{${"core_id"}}`, encodeURIComponent(String(coreId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)

            if (restartNodes !== undefined) {
                localVarQueryParameter['restart_nodes'] = restartNodes;
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(coreCreate, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * restart nodes related to the core config
         * @summary Restart Core
         * @param {number} coreId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        restartCore: async (coreId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'coreId' is not null or undefined
            assertParamExists('restartCore', 'coreId', coreId)
            const localVarPath = `/api/core/{core_id}/restart`
                .replace(`{${"core_id"}}`, encodeURIComponent(String(coreId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CoreApi - functional programming interface
 * @export
 */
export const CoreApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CoreApiAxiosParamCreator(configuration)
    return {
        /**
         * Create a new core configuration.
         * @summary Create Core Config
         * @param {CoreCreate} coreCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createCoreConfig(coreCreate: CoreCreate, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CoreResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createCoreConfig(coreCreate, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CoreApi.createCoreConfig']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Delete a core configuration.
         * @summary Delete Core Config
         * @param {number} coreId 
         * @param {boolean} [restartNodes] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteCoreConfig(coreId: number, restartNodes?: boolean, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteCoreConfig(coreId, restartNodes, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CoreApi.deleteCoreConfig']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get a list of all core configurations.
         * @summary Get All Cores
         * @param {number | null} [offset] 
         * @param {number | null} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllCores(offset?: number | null, limit?: number | null, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CoreResponseList>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllCores(offset, limit, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CoreApi.getAllCores']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get a core configuration by its ID.
         * @summary Get Core Config
         * @param {number} coreId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCoreConfig(coreId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CoreResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCoreConfig(coreId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CoreApi.getCoreConfig']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Update an existing core configuration.
         * @summary Modify Core Config
         * @param {number} coreId 
         * @param {boolean} restartNodes 
         * @param {CoreCreate} coreCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async modifyCoreConfig(coreId: number, restartNodes: boolean, coreCreate: CoreCreate, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CoreResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.modifyCoreConfig(coreId, restartNodes, coreCreate, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CoreApi.modifyCoreConfig']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * restart nodes related to the core config
         * @summary Restart Core
         * @param {number} coreId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async restartCore(coreId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.restartCore(coreId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CoreApi.restartCore']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * CoreApi - factory interface
 * @export
 */
export const CoreApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CoreApiFp(configuration)
    return {
        /**
         * Create a new core configuration.
         * @summary Create Core Config
         * @param {CoreCreate} coreCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createCoreConfig(coreCreate: CoreCreate, options?: RawAxiosRequestConfig): AxiosPromise<CoreResponse> {
            return localVarFp.createCoreConfig(coreCreate, options).then((request) => request(axios, basePath));
        },
        /**
         * Delete a core configuration.
         * @summary Delete Core Config
         * @param {number} coreId 
         * @param {boolean} [restartNodes] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteCoreConfig(coreId: number, restartNodes?: boolean, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteCoreConfig(coreId, restartNodes, options).then((request) => request(axios, basePath));
        },
        /**
         * Get a list of all core configurations.
         * @summary Get All Cores
         * @param {number | null} [offset] 
         * @param {number | null} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllCores(offset?: number | null, limit?: number | null, options?: RawAxiosRequestConfig): AxiosPromise<CoreResponseList> {
            return localVarFp.getAllCores(offset, limit, options).then((request) => request(axios, basePath));
        },
        /**
         * Get a core configuration by its ID.
         * @summary Get Core Config
         * @param {number} coreId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCoreConfig(coreId: number, options?: RawAxiosRequestConfig): AxiosPromise<CoreResponse> {
            return localVarFp.getCoreConfig(coreId, options).then((request) => request(axios, basePath));
        },
        /**
         * Update an existing core configuration.
         * @summary Modify Core Config
         * @param {number} coreId 
         * @param {boolean} restartNodes 
         * @param {CoreCreate} coreCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        modifyCoreConfig(coreId: number, restartNodes: boolean, coreCreate: CoreCreate, options?: RawAxiosRequestConfig): AxiosPromise<CoreResponse> {
            return localVarFp.modifyCoreConfig(coreId, restartNodes, coreCreate, options).then((request) => request(axios, basePath));
        },
        /**
         * restart nodes related to the core config
         * @summary Restart Core
         * @param {number} coreId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        restartCore(coreId: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.restartCore(coreId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CoreApi - object-oriented interface
 * @export
 * @class CoreApi
 * @extends {BaseAPI}
 */
export class CoreApi extends BaseAPI {
    /**
     * Create a new core configuration.
     * @summary Create Core Config
     * @param {CoreCreate} coreCreate 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CoreApi
     */
    public createCoreConfig(coreCreate: CoreCreate, options?: RawAxiosRequestConfig) {
        return CoreApiFp(this.configuration).createCoreConfig(coreCreate, options).then((request) => request(this.axios, this.basePath)).then(({data}) => data);
    }

    /**
     * Delete a core configuration.
     * @summary Delete Core Config
     * @param {number} coreId 
     * @param {boolean} [restartNodes] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CoreApi
     */
    public deleteCoreConfig(coreId: number, restartNodes?: boolean, options?: RawAxiosRequestConfig) {
        return CoreApiFp(this.configuration).deleteCoreConfig(coreId, restartNodes, options).then((request) => request(this.axios, this.basePath)).then(({data}) => data);
    }

    /**
     * Get a list of all core configurations.
     * @summary Get All Cores
     * @param {number | null} [offset] 
     * @param {number | null} [limit] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CoreApi
     */
    public getAllCores(offset?: number | null, limit?: number | null, options?: RawAxiosRequestConfig) {
        return CoreApiFp(this.configuration).getAllCores(offset, limit, options).then((request) => request(this.axios, this.basePath)).then(({data}) => data);
    }

    /**
     * Get a core configuration by its ID.
     * @summary Get Core Config
     * @param {number} coreId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CoreApi
     */
    public getCoreConfig(coreId: number, options?: RawAxiosRequestConfig) {
        return CoreApiFp(this.configuration).getCoreConfig(coreId, options).then((request) => request(this.axios, this.basePath)).then(({data}) => data);
    }

    /**
     * Update an existing core configuration.
     * @summary Modify Core Config
     * @param {number} coreId 
     * @param {boolean} restartNodes 
     * @param {CoreCreate} coreCreate 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CoreApi
     */
    public modifyCoreConfig(coreId: number, restartNodes: boolean, coreCreate: CoreCreate, options?: RawAxiosRequestConfig) {
        return CoreApiFp(this.configuration).modifyCoreConfig(coreId, restartNodes, coreCreate, options).then((request) => request(this.axios, this.basePath)).then(({data}) => data);
    }

    /**
     * restart nodes related to the core config
     * @summary Restart Core
     * @param {number} coreId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CoreApi
     */
    public restartCore(coreId: number, options?: RawAxiosRequestConfig) {
        return CoreApiFp(this.configuration).restartCore(coreId, options).then((request) => request(this.axios, this.basePath)).then(({data}) => data);
    }
}

