/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CoreCreate,
  CoreResponse,
  CoreResponseList,
  Forbidden,
  HTTPValidationError,
  Unauthorized,
} from '../models/index';
import {
    CoreCreateFromJSON,
    CoreCreateToJSON,
    CoreResponseFromJSON,
    CoreResponseToJSON,
    CoreResponseListFromJSON,
    CoreResponseListToJSON,
    ForbiddenFromJSON,
    ForbiddenToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    UnauthorizedFromJSON,
    UnauthorizedToJSON,
} from '../models/index';

export interface CreateCoreConfigRequest {
    coreCreate: CoreCreate;
}

export interface DeleteCoreConfigRequest {
    coreId: number;
    restartNodes?: boolean;
}

export interface GetAllCoresRequest {
    offset?: number | null;
    limit?: number | null;
}

export interface GetCoreConfigRequest {
    coreId: number;
}

export interface ModifyCoreConfigRequest {
    coreId: number;
    restartNodes: boolean;
    coreCreate: CoreCreate;
}

export interface RestartCoreRequest {
    coreId: number;
}

/**
 * 
 */
export class CoreApi extends runtime.BaseAPI {

    /**
     * Create a new core configuration.
     * Create Core Config
     */
    async createCoreConfigRaw(requestParameters: CreateCoreConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CoreResponse>> {
        if (requestParameters['coreCreate'] == null) {
            throw new runtime.RequiredError(
                'coreCreate',
                'Required parameter "coreCreate" was null or undefined when calling createCoreConfig().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }

        const response = await this.request({
            path: `/api/core`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CoreCreateToJSON(requestParameters['coreCreate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CoreResponseFromJSON(jsonValue));
    }

    /**
     * Create a new core configuration.
     * Create Core Config
     */
    async createCoreConfig(requestParameters: CreateCoreConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CoreResponse> {
        const response = await this.createCoreConfigRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a core configuration.
     * Delete Core Config
     */
    async deleteCoreConfigRaw(requestParameters: DeleteCoreConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['coreId'] == null) {
            throw new runtime.RequiredError(
                'coreId',
                'Required parameter "coreId" was null or undefined when calling deleteCoreConfig().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['restartNodes'] != null) {
            queryParameters['restart_nodes'] = requestParameters['restartNodes'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }

        const response = await this.request({
            path: `/api/core/{core_id}`.replace(`{${"core_id"}}`, encodeURIComponent(String(requestParameters['coreId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a core configuration.
     * Delete Core Config
     */
    async deleteCoreConfig(requestParameters: DeleteCoreConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteCoreConfigRaw(requestParameters, initOverrides);
    }

    /**
     * Get a list of all core configurations.
     * Get All Cores
     */
    async getAllCoresRaw(requestParameters: GetAllCoresRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CoreResponseList>> {
        const queryParameters: any = {};

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }

        const response = await this.request({
            path: `/api/cores`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CoreResponseListFromJSON(jsonValue));
    }

    /**
     * Get a list of all core configurations.
     * Get All Cores
     */
    async getAllCores(requestParameters: GetAllCoresRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CoreResponseList> {
        const response = await this.getAllCoresRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a core configuration by its ID.
     * Get Core Config
     */
    async getCoreConfigRaw(requestParameters: GetCoreConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CoreResponse>> {
        if (requestParameters['coreId'] == null) {
            throw new runtime.RequiredError(
                'coreId',
                'Required parameter "coreId" was null or undefined when calling getCoreConfig().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }

        const response = await this.request({
            path: `/api/core/{core_id}`.replace(`{${"core_id"}}`, encodeURIComponent(String(requestParameters['coreId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CoreResponseFromJSON(jsonValue));
    }

    /**
     * Get a core configuration by its ID.
     * Get Core Config
     */
    async getCoreConfig(requestParameters: GetCoreConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CoreResponse> {
        const response = await this.getCoreConfigRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update an existing core configuration.
     * Modify Core Config
     */
    async modifyCoreConfigRaw(requestParameters: ModifyCoreConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CoreResponse>> {
        if (requestParameters['coreId'] == null) {
            throw new runtime.RequiredError(
                'coreId',
                'Required parameter "coreId" was null or undefined when calling modifyCoreConfig().'
            );
        }

        if (requestParameters['restartNodes'] == null) {
            throw new runtime.RequiredError(
                'restartNodes',
                'Required parameter "restartNodes" was null or undefined when calling modifyCoreConfig().'
            );
        }

        if (requestParameters['coreCreate'] == null) {
            throw new runtime.RequiredError(
                'coreCreate',
                'Required parameter "coreCreate" was null or undefined when calling modifyCoreConfig().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['restartNodes'] != null) {
            queryParameters['restart_nodes'] = requestParameters['restartNodes'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }

        const response = await this.request({
            path: `/api/core/{core_id}`.replace(`{${"core_id"}}`, encodeURIComponent(String(requestParameters['coreId']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: CoreCreateToJSON(requestParameters['coreCreate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CoreResponseFromJSON(jsonValue));
    }

    /**
     * Update an existing core configuration.
     * Modify Core Config
     */
    async modifyCoreConfig(requestParameters: ModifyCoreConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CoreResponse> {
        const response = await this.modifyCoreConfigRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * restart nodes related to the core config
     * Restart Core
     */
    async restartCoreRaw(requestParameters: RestartCoreRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['coreId'] == null) {
            throw new runtime.RequiredError(
                'coreId',
                'Required parameter "coreId" was null or undefined when calling restartCore().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }

        const response = await this.request({
            path: `/api/core/{core_id}/restart`.replace(`{${"core_id"}}`, encodeURIComponent(String(requestParameters['coreId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * restart nodes related to the core config
     * Restart Core
     */
    async restartCore(requestParameters: RestartCoreRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.restartCoreRaw(requestParameters, initOverrides);
    }

}
