/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Forbidden,
  General,
  HTTPValidationError,
  SettingsSchemaInput,
  SettingsSchemaOutput,
  Unauthorized,
} from '../models/index';
import {
    ForbiddenFromJSON,
    ForbiddenToJSON,
    GeneralFromJSON,
    GeneralToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    SettingsSchemaInputFromJSON,
    SettingsSchemaInputToJSON,
    SettingsSchemaOutputFromJSON,
    SettingsSchemaOutputToJSON,
    UnauthorizedFromJSON,
    UnauthorizedToJSON,
} from '../models/index';

export interface ModifySettingsRequest {
    settingsSchemaInput: SettingsSchemaInput;
}

/**
 * 
 */
export class SettingsApi extends runtime.BaseAPI {

    /**
     * Get General Settings
     */
    async getGeneralSettingsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<General>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }

        const response = await this.request({
            path: `/api/settings/general`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GeneralFromJSON(jsonValue));
    }

    /**
     * Get General Settings
     */
    async getGeneralSettings(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<General> {
        const response = await this.getGeneralSettingsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get Settings
     */
    async getSettingsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SettingsSchemaOutput>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }

        const response = await this.request({
            path: `/api/settings`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SettingsSchemaOutputFromJSON(jsonValue));
    }

    /**
     * Get Settings
     */
    async getSettings(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SettingsSchemaOutput> {
        const response = await this.getSettingsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Modify Settings
     */
    async modifySettingsRaw(requestParameters: ModifySettingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SettingsSchemaOutput>> {
        if (requestParameters['settingsSchemaInput'] == null) {
            throw new runtime.RequiredError(
                'settingsSchemaInput',
                'Required parameter "settingsSchemaInput" was null or undefined when calling modifySettings().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }

        const response = await this.request({
            path: `/api/settings`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: SettingsSchemaInputToJSON(requestParameters['settingsSchemaInput']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SettingsSchemaOutputFromJSON(jsonValue));
    }

    /**
     * Modify Settings
     */
    async modifySettings(requestParameters: ModifySettingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SettingsSchemaOutput> {
        const response = await this.modifySettingsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
